### PR TITLE
[WIP]3943 statistical data summary tables

### LINKED ISSUE #3943: Implement filterable campaign finance data summaries
### Summary

**What we're after:**
_Implement filterable campaign finance data summary section and committee type tables._

**Sample prototypes on feature space:**
- [Congressional candidate data summary tables](https://fec-feature-cms.app.cloud.gov/campaign-finance-data/congressional-candidate-data-summary-tables/)
- [Presidential candidate data summary tables](https://fec-feature-cms.app.cloud.gov/campaign-finance-data/presidential-candidate-data-summary-tables/)
- [Party committee data summary tables](https://fec-feature-cms.app.cloud.gov/campaign-finance-data/party-committee-data-summary-tables/)
- [Political action committee data summary tables](https://fec-feature-cms.app.cloud.gov/campaign-finance-data/pac-data-summary-tables/)
- [Communication filings data summary tables](https://fec-feature-cms.app.cloud.gov/campaign-finance-data/communication-filings-data-summary-tables/)

### Related issues

- #3816 (design work)
- #4052 (file migration)

### Requirements and technical steps
- Finalize the naming for this data summary section
- Ensure that the [spreadsheet](https://docs.google.com/spreadsheets/d/1fpqKiHy_PAZU5gN6mV0NO0Wow-bpx98W3ct2b2K9T3Q/edit#gid=0) of summary data is accurate
    - Add archived data summaries to spreadsheet
- Create filter capability based on two year period and data summary segment
- Should be able to click on a link to come to a pre-filtered table by two year period and data summary segment
- Migrate all PDF and Excel file resources to the content-s3 bucket **(This has beed moved to https://github.com/fecgov/fec-cms/issues/4052)**
- Delete PDF and Excel files from transition after it's migrated **(This has beed moved to https://github.com/fecgov/fec-cms/issues/4052)**

### Completion criteria
- [ ] New data summary by committee type pages is created
- [ ] Create redirect from the transition data summary pages to the new landing page for data summaries
### Future work

_Other future work that may be needed following this issue's completion._

### PR DESCRIPTION
**Pull request by johnnyporkchops**
## Summary

- Resolves #3943
_Include a summary of proposed changes._

## Impacted areas of the application
new_file:   fec/static/js/pages/statistical-summary.js
modified: fec/home/models.py
new_file: fec/home/migrations/0110_auto_20200921_0151.py
modified: fec/home/templates/home/custom_page.html
modified:   fec/static/scss/components/_table-styles.scss

Please ignore updated requirements.txt and tasks.py., those will ultimately not be part of the PR

 

## Screenshots

- _Include a screenshot of the new/updated features in context (“in the wild”). If it is an interface or front-end change, include both Before and After screenshots._

## Related PRs

List related PRs against other branches:

branch | PR
------ | ------
fix/other_pr | [link]()
feature/other_pr | [link]()

## How to test

Include any information that may be helpful to the reviewer(s).
_This might include:_

- links to sample pages to test
- Any local environmental setup that is unusual (env vars, API version to point to, etc)

____

### CODE REVIEW

**Comment by JonellaCulmer** [comment]
@johnnyporkchops I took a look at a few of the pages. Here is an annotated screenshot with comments:
Screen Shot 2020-09-29 at 1 28 00 PM

**Comment by johnnyporkchops** [comment]
@JonellaCulmer Can you clarify for me an example of a press release link

**Comment by johnnyporkchops** [comment]
Closing in favor of 
https://github.com/fecgov/fec-cms/pull/4088

**Comment by johnnyporkchops** [comment]
I am re-opening this WIP PR to push latest changes to feature. Because my non-WIP branch has a different Django migration file, pushing that to feature causes conflicts. Normally the solution would be to restore feature database to latest dump and push the new branch...BUT, I have prototyped Wagtail pages there I do not want to overwrite!

**Pull request closed without merging**
