### PR TITLE
feature/4189 cross origin links

### LINKED ISSUE #4189: Optimization (accessibility): Links to cross-origin destinations are unsafe
### Background
Looking to [optimize the site's performance](https://github.com/fecgov/fec-cms/issues/3711) and that of the homepage specifically, the Lighthouse tool in Chromium browsers has made some suggestions. Some of these will have repercussions throughout the app so we're going to make them their own tickets.

# Best Practices Recommendation: Links to cross-origin destinations are unsafe
Add `rel="noopener"` or `rel="noreferrer"` to any external links to improve performance and prevent security vulnerabilities. [details](https://web.dev/external-anchors-use-rel-noopener/?utm_source=lighthouse&utm_medium=devtools)

## Overview
Should we add a `rel` rule to the footer link to govdelivery?

## Benefit (the 80 of 80/20)
Minimal in this case

## Effort (the 20 of 80/20)
Tiny—this ticket is more complicated than the work

## Complications
None?

#### Related tickets
- [Preload key requests](https://github.com/fecgov/fec-cms/issues/4168)
- [Remove unused JavaScript](https://github.com/fecgov/fec-cms/issues/4169)
- [Remove unused CSS](https://github.com/fecgov/fec-cms/issues/4170)
- [Preconnect to required origins](https://github.com/fecgov/fec-cms/issues/4171)
- [Eliminate render-blocking resources](https://github.com/fecgov/fec-cms/issues/4172)
- [Ensure text remains visible during webfont load](https://github.com/fecgov/fec-cms/issues/4173)
- [Reduce the impact of third-party code](https://github.com/fecgov/fec-cms/issues/4175)
- [Does not use passive listeners to improve scrolling performance](https://github.com/fecgov/fec-cms/issues/4176)
- [Image elements do not have explicit width and height](https://github.com/fecgov/fec-cms/issues/4177)
- [Serve static assets with an efficient cache policy](https://github.com/fecgov/fec-cms/issues/4178)
- [Minimize main-thread work](https://github.com/fecgov/fec-cms/issues/4179)
- [Avoid an excessive DOM size](https://github.com/fecgov/fec-cms/issues/4180)
- [Reduce JavaScript execution time](https://github.com/fecgov/fec-cms/issues/4181)
- [Avoid enormous network payloads](https://github.com/fecgov/fec-cms/issues/4182)
- [[aria-hidden="true"] elements contain focusable descendents](https://github.com/fecgov/fec-cms/issues/4183)
- [Elements with an ARIA [role] that require children to contain a specific [role] are missing some or all of those required children](https://github.com/fecgov/fec-cms/issues/4184)
- [[aria-*] attributes do not have valid values](https://github.com/fecgov/fec-cms/issues/4185)
- [ARIA IDs are not unique](https://github.com/fecgov/fec-cms/issues/4186)
- [Lists do not contain only <li> elements and script supporting elements (<script> and <template>)](https://github.com/fecgov/fec-cms/issues/4187)
- [[user-scalable="no"] is used in the <meta name="viewport"> element or the [maximum-scale] attribute is less than 5](https://github.com/fecgov/fec-cms/issues/4188)
- [Serves images with low resolution](https://github.com/fecgov/fec-cms/issues/4190)

### PR DESCRIPTION
**Pull request by rfultz**
## Summary

- Resolves #4189 

Lighthouse was warning us about links on our homepage that target `_blank`, that we should add `noopener` or `noreferrer` rules. Investigating the homepage, the only `target="_blank"` was the "upgrade your browser from IE" link to Browse Happy. So I added rules the `noreferrer` rule because do they really care/need to know that we may be linking some people to them?

Google's [definition](https://web.dev/external-anchors-use-rel-noopener/?utm_source=lighthouse&utm_medium=devtools):
> `rel="noopener"` prevents the new page from being able to access the window.opener property and ensures it runs in a separate process.
> `rel="noreferrer"` has the same effect but also prevents the Referrer header from being sent to the new page.

Then I started looking through the rest of the site.

This was my logic in making the changes I did:
- we don't need either for any links on our domain, so remove the rule for any links that are always internal.
- make it more clear that those are internal links (like changing `https://www.fec.gov/contact/` to `/contact/`)
- `noreferrer` as a starting point, being the most secure (Google, YouTube, 
- `noopener` when we may want to let others know that we're sending traffic to them (e.g., govdelivery)
- make a note (`NOREFERRER,NOOPENER?`) where I'm not sure which option may be best

**POSSIBLE ADDITIONAL CHANGES**
Is there any field in Wagtail that we should probably tighten a URL's `<a>` in the template?

### Required reviewers

Two?

## Impacted areas of the application

Potentially every off-site link. The only place I think it could remotely matter is for our GovDelivery, Google Calendar, or YouTube links.

## Screenshots

No visual changes

## Related PRs

None

## How to test

- pull the branch
- `./manage.py runserver`
- click some of these links to make sure they work
- Can run a Lighthouse scan on the homepage and any pages that used to have a `target="_blank"` but now includes `noopener` or `noreferrer`
- Should check that the Google Calendar links still work
- Are our GovDelivery or YouTube links breaking? (They could provide more information from us than this PR will let them see, but may be fine, too)

### CODE REVIEW

**Comment by rfultz** [comment]
Removing the WIP from this. I just tightened the document links to `noreferrer` since it won't affect links on our own domains. If we need to change, we can.

**Review by patphongs — APPROVED** [review]
This looks good to me @rfultz, the link to browsehappy.com will eventually be removed in this PR too, but no need to change anything here: https://github.com/fecgov/fec-cms/pull/4649

**Comment by johnnyporkchops** [comment]
@rfultz , From How-to-test: "Should check that the Google Calendar links still work"
You could probably add `npm run build-js` to How-to-test since it includes changes to compiled handlebar templates. Were you able to confirm that the Google calendar links work (after building js) locally,  before pushing the PR?

**Review by johnnyporkchops — APPROVED** [review]
Looks good to me. As far as I can tell the Calendar links and GovDel  still work for subscriptions when testing locally. Not sure about Youtube links

**Pull request merged**
