### PR TITLE
[On Hold] Add content security policy headers

### LINKED ISSUE #3069: [Tenable] CMS missing/inadequate headers (due 8/31/19)
### 1. Missing 'Cache-Control' Header 
The HTTP 'Cache-Control' header is used to specify directives for caching mechanisms. The server did not return a 'Cache-Control' header which means page containing sensitive information (password, credit card, personal data, social security number, etc) could be stored on client side disk and then be exposed to unauthorised persons. This URL is flagged as a specific example: fec-dev-cms.app.cloud.gov 
Remediation path: Configure your web server to include a 'Cache-Control' header with appropriate directives. If page contains sensitive information 'Cache-Control' value should be 'no-cache, no-store' and 'Pragma' header value should be 'no-cache'. 
References: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Pragma; https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control; https://www.owasp.org/index.php/Testing_for_Browser_cache_weakness_(OTG-AUTHN-006)
### 2. Missing Content Security Policy 
Content Security Policy (CSP) is a web security standard that helps to mitigate attacks like cross-site scripting (XSS), clickjacking or mixed content issues. CSP provides mechanisms to websites to restrict content that browsers will be allowed to load. No CSP header has been detected on this host. This URL is flagged as an specific example: fec-dev-cms.app.cloud.gov 
Remediation path: Configure Content Security Policy on your website by adding 'Content-Security-Policy' HTTP header or meta tag http-equiv='Content-Security-Policy'. 
References: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy; https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP; https://csp-evaluator.withgoogle.com/; https://developers.google.com/web/fundamentals/security/csp/; https://content-security-policy.com/

**To do**
- [ ] Front end investigates use of Engine X or the CMS application itself to investigate headers. (Also, are there core settings?)

### PR DESCRIPTION
**Pull request by patphongs**
## Summary

- Resolves #3069 
_This adds content security policy headers to every page on our website._

## Impacted areas of the application
List general components of the application that this PR will affect:

-  This will impact everything on our website. Need to make sure that there are no loading errors for anything we pull into our site like api calls, scripts, images, fonts, etc. 

## Screenshots

None, this is pure code

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
openFEC/feature/3876-add-response-headers | [link](https://github.com/fecgov/openFEC/pull/3891)

## How to test
Check each template type to make sure that the content security policy is not interfering with anything we're pulling into the site.
- [ ] Homepage
- [ ] Data landing
- [ ] Election search page
- [ ] All datatable pages
- [ ] Candidate profile pages
- [ ] Committee profile pages
- [ ] Election profile pages
- [ ] Wagtail admin (creating new pages, updating pages, saving pages, adding new block components)
- [x] Wagtail generated pages
- [x] Legal resource pages

For developers, open up your inspector console and look for errors like this: 

"Refused to load the script 'https://example.gov' because it violates the following Content Security Policy directive:..."

### CODE REVIEW

**Comment by rfultz** [comment]
> Pat - have found one item in Wagtail that seemed strange. I'm unable to move files from where they were published into another location. We definitely need that ability since sometimes people accidentally forget to publish things into the Updates folder and instead publish to Home.

@dorothyyeager, which browser were you using? Did you get any error messages? Any sound effects or other unusual behavior?

**Comment by dorothyyeager** [comment]
@rfultz Tested using Chrome. No weird sound effects. I do get this error message: 
image

**Comment by patphongs** [comment]
@dorothyyeager It appears that the legal resource 404 error is because that section isn't set up on our feature site. The path exists on our other test environments though, so I don't anticipate any issues there.

As for the pages not being able to move, I don't think it's related to the CSP. I think it's because some pages are allowed under certain directories and some are not. I get the following django error when I try to move a page from the home directory to the updates section: AttributeError: 'NoneType' object has no attribute 'allowed_subpage_models'

**Comment by dorothyyeager** [comment]
Approved since the issue I flagged does not appear to relate to the CMS headers.

**Comment by lbeaufort** [comment]
Closing in favor of #3124

**Pull request closed without merging**
