### PR TITLE
Feature/candidate filings tab new

### LINKED ISSUE #2154: Create Filings tab and add image number to filings on candidate profile pages
**What we're after:** To add more clarity and consistency across our profile pages, we need to create a Filings tab and move the bulk of candidate filings to that section. 

While we plan to create that tab, we also need to keep the candidate's current version of their Statement of candidacy on the `About this candidate` tab. That way, users familiar with this placement will not be without it, or we introduce a pain point for them. Additional work is outlined below in the completion criteria, include the addition of filing image number to the tables. 

**Completion criteria:**
- [x] Create "Filings" tab, list last after "Spending by others to support or oppose"
- [x] Add logic to "About this candidate" tab to list only the candidate's current version of their Form 2 Statement of candidacy
- [x] Create a 'Statements of candidacy' table on "Filings" tab, include all versions including current version
- [x] Move `Other documents` table from "About this candidate" tab to "Filings" tab. This table should follow the `Statements of candidacy` table
- [x] Include document "Image number" in `Statements of candidacy` table. Order of columns should be: Document > Version > Date filed > **Image number** > Pages
- [x] Update side nav and subnav items to correspond with new sections. Under Filings, Statements or candidacy and Other documents should be listed. Under About this candidate, Candidate information and Committees should be listed, and Other documents removed. 

**Designs:**

## Update about this candidate page
screen shot 2018-07-16 at 8 27 30 am

## New filings page
Information such as documents and image number columns are truncated to fit the mockup, but in production no overlap of graphics and text, or truncation of numbers should occur.
screen shot 2018-07-10 at 11 04 18 am

### PR DESCRIPTION
**Pull request by johnnyporkchops**
## Summary
Create candidate filings tab with Statements of candidacy and other documents files tables.
**This replaces PR https://github.com/fecgov/fec-cms/pull/2252. Please see the conversation there for history.**
- Resolves #2154

### CODE REVIEW

**Comment by johnnyporkchops** [comment]
@jonella, I removed the coverage dates filter tag (the tag that specifies the dates being shown in the tables) because that is tied to the election years dropdown select. But should I attempt to find a way to show what years are covered for each candidate based on the documents returned by the table or should we say "All statements of candidacy" and 'All other documents filed'?

**Comment by JonellaCulmer** [comment]
@johnnyporkchops I'm looking into your question above about addressing "All statements of candidacy" in a meaningful way. In the meantime, I noticed this: 

The export button for these reports is going rogue and sitting to the left of the table with form 2s. It's pushing the table over, and out of alignment with the table below it.
Screenshot:
screen shot 2018-08-29 at 1 50 14 pm

**Comment by johnnyporkchops** [comment]
@JonellaCulmer , I found a way to show all the election years covered for the tables on the filings tab (Statements of candidacy and Other documents filed). Let me know if this makes sense or if you still want to just go with `"All statements of candidacy"`
screen shot 2018-08-31 at 10 48 40 pm

**Comment by johnnyporkchops** [comment]
This branch has been rebased on top of  `develop`  to pickup relevant changes made in PR #2320 for better local testing.

**Comment by lbeaufort** [comment]
@johnnyporkchops thanks for all your hard work on this!

I think this candidate should have a statement of candidacy for 2018: http://localhost:8000/data/candidate/H0TX09168/?tab=filings
screen shot 2018-09-04 at 9 51 01 am
https://www.fec.gov/data/filings/?data_type=processed&candidate_id=H0TX09168

**Comment by johnnyporkchops** [comment]
One problem with the [coverage dates for filings tab](https://github.com/fecgov/fec-cms/pull/2310#issuecomment-417827550) tables is that elections is the filter being used, and for example, this candidate says 2022 for the thru date.
http://localhost:8000/data/candidate/S6AZ00019/?tab=filings

**Comment by johnnyporkchops** [comment]
@laura, Good catch. So I originally added a check for null based on existence of `two_year_totals.coverage_start_date` for this review request: of https://github.com/fecgov/fec-cms/pull/2252#pullrequestreview-144674465. Now that we are not filtering filings tab based on a dropdown filter for elections. I will remove this check  and  `S6AZ00019` will return a table populated with SOC.

**Comment by patphongs** [comment]
We have decided to remove coverage dates from the new candidate filings tab for now until we can figure out a better way to implement it. New implementation issue has been created for that here: https://github.com/fecgov/fec-cms/issues/2333

**Comment by lbeaufort** [comment]
@johnnyporkchops two questions:

1) Does the "Export" button work for you? There might be an issue with the button. https://github.com/fecgov/fec-cms/pull/2310/files#diff-3799ed5dff417ccd5f3dc456f38c7a57R22
2) The "Filter this data" button is being passed cycle, so it doesn't filter the same results as the data table. I think we can just remove the cycle parameter.

**Comment by johnnyporkchops** [comment]
@laura, thanks for [catching this too](https://github.com/fecgov/fec-cms/pull/2310#issuecomment-418867175). I was not sure about the `export button` because there is not one on the original mockup, but there is one on committee filings tab. So the `export` and `filter this data` buttons work now for SOC table. And I added `filter this data` for Other documents filed. 
@jonella, some of this departs from the mockup, but I took some license since the format has changed since mockup. Just let me know what stays and what goes.

**Comment by lbeaufort** [comment]
@johnnyporkchops looks good. I confirmed that "Disavowal notice" and "Miscellaneous Report TO FEC" appear in the "Other Documents" section, but I think "RFAI: Document" (RFAI's for Form 2) should appear with the Statements of Candidacy.

screen shot 2018-09-06 at 8 26 00 am


example: Misc report OK, RFAI not in right spot - http://localhost:8000/data/candidate/P60023777/?tab=filings#other
example: Disavowal OK: http://localhost:8000/data/candidate/H6IL11117/?tab=filings#other

cc: @llienfec

**Pull request merged**
