### PR TITLE
Limit 10 candidates for contribution by size and state

### LINKED ISSUE #6226: Make contributions by state filter updates
### What we're after
Need to update the front-end filter for the individual contributions by state filter on election profile pages
Example: https://www.fec.gov/data/elections/senate/FL/2024/#individual-contributions

### Related issues/PRs
- https://github.com/fecgov/fec-cms/issues/6186

- Blocking https://github.com/fecgov/openFEC/pull/5779

### Design
Screenshot 2024-04-10 at 10 18 10 AM

### Completion criteria
- [ ] Contributions by state filter is update to clearly distinguish between 10 selected committees and any additional filters not selected as well as additional text to clarify the 10 candidate limit

### Future work: 
Consider making the "x" next to unselected filters persistent globally and not only show on rollover because mobile devices do not have rollover state.

### PR DESCRIPTION
**Pull request by johnnyporkchops**
## Summary (required)
- Limit the candidates selected on contribution by size and state to 10
- As explained in this comment:
https://github.com/fecgov/fec-cms/issues/6186#issuecomment-2047690409

- Resolves #6226

### Required reviewers
One developer, One UX

## Impacted areas of the application
Election page, Contributions by size and state 
modified:   fec/static/js/modules/tables.js
modified:   fec/static/scss/components/_dropdowns.scss
 

## Screenshots

(Include a screenshot of the new/updated features in context (“in the wild”). If it is an interface change, include both before and after screenshots)

## How to test
- [ ] ****** Remove feature deploy task before merge ******
-  `npm run build`
- `npm run test-single`
- Go to an election profile page, individual contribution tab: Example: http://127.0.0.1:8000/data/elections/senate/FL/2024/#individual-contributions
- You should only be able to have 10 candidates' checkboxes checked 
- Checkboxes above 10 should be disabled 
- The dropdown should  be enabled only when there are less than 10 checked
- Only the candidates added from the dropdown, can be removed with the "x" next to the box whether they are checked, unchecked or disabled
- For reference, this comment describes the overall expected behavior for this interface.https://github.com/fecgov/fec-cms/issues/6186#issuecomment-2047690409

### CODE REVIEW

**Comment by JonellaCulmer** [comment]
@johnnyporkchops The only thing I notice, and something that also appears on production, is the dropdown to select additional names, does not stay left-aligned. Is this something you can add to your PR?

Everything else looks great.

**Comment by johnnyporkchops** [comment]
> The only thing I notice, and something that also appears on production, is the dropdown to select additional names, does not stay left-aligned. Is this something you can add to your PR?

@JonellaCulmer ,  Please take a look now, the dropdown should remain left-aligned

**Review by rfultz — APPROVED** [review]
Woo hoo!

**Review by JonellaCulmer — APPROVED** [review]
Everything looks great, thanks @johnnyporkchops

**Review by patphongs — APPROVED** [review]
👍

**Pull request merged**
