### PR TITLE
Logging statements added via wagtail hooks

### PR DESCRIPTION
**Pull request by jontours**
Coincidentally this was the strategy I last looked at before stepping away from this work.  It's really the best way to add this feature that is really idempotent to the functioning of the CMS.  I wish they called them callbacks vice hooks however.

### CODE REVIEW

**Comment by LindsayYoung** [comment]
We do want to review this. The hooks upstream in wagtail were merged into master.  There is a chance we will have to update wagtail first depending on how the release cycle works.

The upstream hooks:
https://github.com/wagtail/wagtail/pull/3722

**Comment by jenniferthibault** [comment]
@LindsayYoung do you know if this work is still relevant? The PR's been open for a while

**Comment by JonellaCulmer** [comment]
@patphongs @johnnyporkchops Are you aware whether this work is still relevant?

**Comment by patphongs** [comment]
User changes are captured within our cms logs now, so this is no longer needed

**Pull request closed without merging**
