### PR TITLE
4509 SNYK LXML

### LINKED ISSUE #4509: [SNYK: MEDIUM] lxml Cross-site scripting (Due: 05/20/2021)
**Overview**
Affected versions of this package are vulnerable to Cross-site Scripting (XSS) via formaction attribute in HTML5.

**Introduced through**
lxml@4.6.2

**Remediation:** Upgrade lxml to version 4.6.3
https://app.snyk.io/vuln/SNYK-PYTHON-LXML-1088006

** Completion criteria:
- [ ] update lxml package to v4.6.3

### PR DESCRIPTION
**Pull request by rfultz**
## Summary

- Resolves #4509 

Snyk reported a vulnerability inside lxml while scrubbing user input. The [release notes](https://pypi.org/project/lxml/4.6.3/) from 4.6.2 to 4.6.3 list only this fix.

### Required reviewers

One front-end and one back-end? (Feel free to edit the list)

## Impacted areas of the application

Anything that uses the lxml package which, for us, is only the scraping and search scripts.

## Screenshots

No visual changes

## Related PRs

None

## How to test

- pull the branch
- `pip install -r requirements.txt`
- `pytest` just in case
- I'd welcome your insight on how to test this when it's only used inside
   - fec/search/management/commands/scrape_cms_pages.py
   - fec/search/management/commands/scrape_transition_pages.py
   - fec/search/management/commands/scrape_web_app_pages.py
   - fec/search/utils/search_indexing.py

### CODE REVIEW

**Review by pkfec — APPROVED** [review]
Ran `snyk test --file=requirements.txt --package-manager=pip` on this feature branch. lxml vulnerability is fixed  in v4.6.3

**Comment by patphongs** [comment]
We should test the scraping scripts to make sure that the JSON outputs for the search.gov indexer still work before merging this PR. Try running the below commands to make sure it still works after upgrading lxml.

```
fec/manage.py scrape_cms_pages
fec/manage.py scrape_web_app_pages
fec/manage.py scrape_transition_pages
```

**Comment by johnnyporkchops** [comment]
We could also run an actual indexing to make sure that works. Can't hurt to do another even thought we just did it

**Review by fec-jli — APPROVED** [review]
test on local, no issue. good job.
run:
pytest
fec/manage.py scrape_cms_pages

one minor thing which is not related with this ticket:
when running: `npm run test-single`
get these two errors (have to use enter key?):
/Users/jli/website-project/cms/fec-cms/fec/fec/static/js/modules/data-map.js
  43:23  error  Replace `['B',·9],·['M',·6],·['K',·3],·['',·0]` with `⏎··['B',·9],⏎··['M',·6],⏎··['K',·3],⏎··['',·0]⏎`  prettier/prettier

/Users/jli/website-project/cms/fec-cms/fec/fec/static/js/modules/maps.js
  30:21  error  Replace `['B',·9],·['M',·6],·['k',·3],·['',·0]` with `⏎··['B',·9],⏎··['M',·6],⏎··['k',·3],⏎··['',·0]⏎`  prettier/prettier

**Comment by rfultz** [comment]
Thanks @fec-jli ! Those are prettier errors (formatting rules). It's a thing right now. On my list is to solve the disconnect between what ESLint wants and what Prettier wants. Prettier is _very_ opinionated and the newest versions changed their rules and they take away more customization options with every release. I'm also looking into replacements so we can make our own rules.

**Review by johnnyporkchops — APPROVED** [review]
Looks good

**Pull request merged**
