### PR TITLE
Fix candidate profile server error in 1988 for Trump

### PR DESCRIPTION
**Pull request by fec-jli**
## Summary (required)
This ticket will fix two issues:
1) one or more of candidate election_years is not exist in fec_cycles_in_election 
ex:Trump P80001571 / 1988, receive a server error page
https://www.fec.gov/data/candidate/P80001571/?cycle=1988&election_full=true

https://fec-dev-api.app.cloud.gov/v1/candidate/P80001571/history/
P80001571

2) candidate only file F2. never in election yet, so fec_cycles_in_election=null.
receive a server error page. ex:P00012799 (2020)
https://www.fec.gov/data/candidate/P00012799/

https://fec-dev-api.app.cloud.gov/v1/candidate/P00012799/history/
P00012799

- Resolves [https://github.com/fecgov/fec-cms/issues/3318]( https://github.com/fecgov/fec-cms/issues/3318)
and [https://github.com/fecgov/fec-cms/issues/3326](https://github.com/fecgov/fec-cms/issues/3326)

## Impacted areas of the application
List general components of the application that this PR will affect:

-  Candidate profile page.

## How to test
1) checkout branch
2) point to dev api
3) run test:
npm run test-single
pytest
 ./manage.py test

4) Test Example candidates and compare with production website.

(1) P80001571 (TRUMP)
prod (get error)
https://www.fec.gov/data/candidate/P80001571/?cycle=1988&election_full=true
local ( message)
http://127.0.0.1:8000/data/candidate/P80001571/?cycle=1988&election_full=true

(2) S2TX00312 (future candidate)
prod:
https://www.fec.gov/data/candidate/S2TX00312/
local (should same as prod)
http://127.0.0.1:8000/data/candidate/S2TX00312/

(3) P00012799 
prod (get error)
https://www.fec.gov/data/candidate/P00012799/
local ( message)
http://127.0.0.1:8000/data/candidate/P00012799/

### CODE REVIEW

**Comment by jason-upchurch** [comment]
@fec-jli @lbeaufort , `'rounded_election_years'` is specified as an array of integers in `public.ofec_candidate_history_vw`. We should not add type casting, i.e., `int(x)`, to the python code.

**Comment by fec-jli** [comment]
> @fec-jli @lbeaufort , `'rounded_election_years'` is specified as an array of integers in `public.ofec_candidate_history_vw`. We should not add type casting, i.e., `int(x)`, to the python code.

Thanks @jason-upchurch I guess you mean fec_cycles_in_election? good catch. has changed.

**Comment by jason-upchurch** [comment]
> > @fec-jli @lbeaufort , `'rounded_election_years'` is specified as an array of integers in `public.ofec_candidate_history_vw`. We should not add type casting, i.e., `int(x)`, to the python code.
> 
> Thanks @jason-upchurch I guess you mean fec_cycles_in_election? good catch. has changed.

@fec-jli I really meant `rounded_election_years` because it looks like we are type casting the elements `int` when they are defined as int already in the database, but I just checked and `fec_cycles_in_election` is also specified as `integer[]` or array of ints, so the same would apply there.

**Comment by jason-upchurch** [comment]
@fec-jli we do appear to be type casting both which is not necessary:
```
    if int(cycle) > latest_fec_cycles_in_election:
        year for year in candidate['fec_cycles_in_election'] if year <= cycle	        max_cycle = int(latest_fec_cycles_in_election)
```

**Comment by fec-jli** [comment]
> > > @fec-jli @lbeaufort , `'rounded_election_years'` is specified as an array of integers in `public.ofec_candidate_history_vw`. We should not add type casting, i.e., `int(x)`, to the python code.
> > 
> > 
> > Thanks @jason-upchurch I guess you mean fec_cycles_in_election? good catch. has changed.
> 
> @fec-jli I really meant `rounded_election_years` because it looks like we are type casting the elements `int` when they are defined as int already in the database, but I just checked and `fec_cycles_in_election` is also specified as `integer[]` or array of ints, so the same would apply there.

Sorry, I did't see anywhere we use int(rounded_election_years), do you pull the latest code? Thanks

**Pull request merged**
