### PR TITLE
Policy and guidance search in CMS

### LINKED ISSUE #3601: Research: Add policy and guidance search to CMS
### Summary

**What we're after:**
_The new policy and guidance search needs to be added into the FEC's CMS interface. This research will be how to pull the fec_content_s3 handle into our website with search results._

### Related issues

_This issue is the overarching implementation issue for the policy and guidance search_

- #3491 

### Completion criteria

- [ ] Able to search correct search handle fec_content_s3
- [ ] Able to display results with title, description, and path

### PR DESCRIPTION
**Pull request by patphongs**
## Summary

- Resolves #3601 
_New guidance document search page. Includes introductory text provided by content team. The search should be able to search defined HTML and PDF pages specified here: https://www.fec.gov/resources/cms-content/documents/sitemap_html.xml and https://www.fec.gov/resources/cms-content/documents/sitemap_pdf.xml_

This feature is under this feature flag: FEC_FEATURE_GUIDANCE_SEARCH. It must be set for go live.

## Impacted areas of the application

List general components of the application that this PR will affect:

-  Application should be fairly independent of other parts of the website. Incorporated this into the search.gov section.

## Screenshots

Screen Shot 2020-03-31 at 2 35 43 PM

Screen Shot 2020-03-31 at 11 30 44 AM

### For design and content:
- This has been deployed to our feature space and is ready for testing: https://fec-feature-cms.app.cloud.gov/legal-resources/policy-and-other-guidance/guidance-documents/

### For developer:
- Pull down this PR
- `export SEARCH_GOV_POLICY_GUIDANCE_KEY` in your environment vars. You can grab this API access key by logging into search.gov and accessing the fec_content_s3 site.
- `export FEC_FEATURE_GUIDANCE_SEARCH = true`
- Go to http://localhost:8000/legal-resources/policy-and-other-guidance/guidance-documents/
- Try performing a search
____

### CODE REVIEW

**Comment by JonellaCulmer** [comment]
@patphongs Looks good so far, here are my thoughts:
- The second sentence starts, "The guidance documents search..." It should say: "This search...
- The button on the search should be gray and with a black magnifying glass
- Fix press release appearance. Example: https://www.fec.gov/updates/fec-statement-on-the-dc-circuit-court-of-appeals-decision-in/

**Comment by patphongs** [comment]
@JonellaCulmer @dorothyyeager Can you look at the no results text as well? Let me know if you think the text should be modified to make it more helpful.

**Comment by JonellaCulmer** [comment]
@patphongs @dorothyyeager We can just change "pages" to "results".

**Comment by patphongs** [comment]
> * The second sentence starts, "The guidance documents search..." It should say: "This search...
> * The button on the search should be gray and with a black magnifying glass
> * Fix press release appearance. Example: https://www.fec.gov/updates/fec-statement-on-the-dc-circuit-court-of-appeals-decision-in/

Thanks @JonellaCulmer, I have made the corrections in bullets 1 & 2. In bullet 3, there's multiple press releases that were found to have bad formatting. @dorothyyeager made a ticket here to fix those: https://github.com/fecgov/fec-cms/issues/3654

**Comment by jason-upchurch** [comment]
We could add "best bets" for all the forms so that if you put in the actual form number, the form is at the top as a suggested result, perhaps followed by the instructions. Well, at least we could _try_ that if it's determined we are ok to actually recommend a result.

**Comment by patphongs** [comment]
@dorothyyeager @JonellaCulmer @jason-upchurch I've done 2 extra things in this feature.

1. Include best bets into the list of results. It will appear as a normal document listing. Only con to this is that it in the normal list of results, can include double results unintentionally. For example, if we have a best bets for the search term "Citizens United" and there are other results that contain that word, a repeated record could show. But a repeated record is better than no record at all.

2. Example text is now included below the search box to show that you can use quotes in your search query

**Pull request merged**
