### PR TITLE
Update boolean search box and add tooltips for AO,MUR, Statutes 

### LINKED ISSUE #2283: Update boolean search box and add tooltip
History: https://github.com/fecgov/fec-cms/issues/2051

**What we're after:** Usability testing revealed that users had trouble understanding they could use boolean symbols in the main search for AOs, MURs and Statutes. Therefore, we have made several changes to the "Find documents with..." pop-up box to help improve their use. 

These changes include:
- [x] Modify/add text to explain what each section of the pop-up accomplishes
  - Section 1 text: Use these search boxes to refine your search:
  - Section 2 text: Use these symbols in the main search box:
- [x] Add an "or" dividing line to make it clear the user has options
- [x] Update the symbols table, removing some of the dividing lines in the mini-table to make it flush with the page a bit more
- [x] Add a tooltip to the "Keyword" search on the main search pages for AOs, MURs and Statutes
  - Tooltip text: Refine a keyword search by using AND, OR, “ ”, -,  to expand or limit results.
- [x] Test on internet explorer, ask content staff since they have a different IE build than devs

### Designs
screen shot 2018-08-14 at 2 30 10 pm

screen shot 2018-08-14 at 2 31 52 pm

### PR DESCRIPTION
**Pull request by johnnyporkchops**
## Summary
Make design/layout edits to keyword modal html and jinja templates
Add tooltip for keyword text-box field on AO, MUR, Statues
 - AO Search is React.js, so I made the tooltip in here, a reusable react component (Could now be 
    used on any filter type inside AO search with custom tooltip message and positioning classes)
 - MUR and Statutes datatables are both  rendered from legal.jinja, so the tooltip is hardcoded there

- Resolves #2283

## Impacted areas of the application
AO Search react app
	- modified:   fec/static/js/legal/Filters.js
	- modified:   fec/static/js/legal/filters/TextFilter.js
	- added:       fec/static/js/legal/filters/TooltipHelp.js
MUR and Statutes datatables:
	- modified:   legal/templates/macros/legal.jinja
        - modified:   fec/static/scss/components/_tooltips.scss
Keyword Modal popup:
        - modified:   home/templates/partials/legal-keyword-modal.html
	- modified:   legal/templates/partials/legal-keyword-modal.jinja
        - modified:   fec/static/scss/components/_search-controls.scss
        - modified:   fec/static/scss/components/_modals.scss

### Tested in Internet Explorer below, per checklist item 5 in issue:
gif2
<hr>

## How to test
Checkout this branch locally: feature/update-boolean-search-box
NPM run build
Runserver and test the tooltips on Keyword text filter on AO, MUR and Statutes searches
Test keyword modal box on the same pages as well as the legal landing page (this uses a different template)
If one were ambitious they could also test the reusable tooltip react component by adding it to `DateFilter.js`* by:
- Copying the tooltip code from the `TextFilter.js` file:
  - Lline 3 
  - Lines 21-27 
  - Line 69 and line 79
...and pasting it into `DateFilter.js`.
- Then enable it in` Filters.js`  for that filter-type (DateFilter), like I did for the  TextFilter (@line 56). Maybe add a different message.
- Don't forget to  run build,  and see if it works! ( I tested it but would still like to see if someone else thinks it works well)

*For filters that depend on other filters, like CheckboxFiler, the process is different, but it can still be added to any filter in the panel.

### CODE REVIEW

**Comment by johnnyporkchops** [comment]
@JonellaCulmer --There are still two minor design issues with this PR that I did not want to hold up the PR getting merged for testing.
1) Tooltips are positioned under the element. The classes we have for above positioning ( `tooltp--above`) are not working properly, and I need to take more time to understand out how to fix this the right way.
2) In Internet Explorer, the "paper-stack" icon does not show adjacent to the keyword modal link for some reason.
These can probably be fixed before you test, but just giving you a heads up.

**Comment by JonellaCulmer** [comment]
That's for the heads up, @johnnyporkchops!

**Comment by JonellaCulmer** [comment]
@johnnyporkchops I can review and approve this, or were you going to try to implement the other stuff before review/merge. Happy to do it either way. Up to you.

**Comment by johnnyporkchops** [comment]
@JonellaCulmer. I pushed fix for outstanding checklist item 1 above. Here are screenshots of how the tooltips render now for this branch (not updated on feature space yet). The one on the `Statutes and MUR pages` needed to be shorter than the mockup to avoid overlapping with the header content. Is this visual inconsistency and issue from a UX POV? 

### AO Page:
screen shot 2018-12-11 at 9 10 06 pm
<hr>

### MUR Page overlap issue:
screen-shot-2018-12-11-at-9 20_overlap
<hr>

### MUR Page w/ overlap fixed:
screen shot 2018-12-11 at 9 11 08 pm

**Pull request merged**
