### PR TITLE
Add new homepage icon links and banner

### LINKED ISSUE #3544: Update homepage with new links to map and other .gov pages
**What we're after:**
As part of the Presidential map work, we need to implement changes to the homepage which creates links to the map. 

### Related issues
- #3500 

Action items: 
- Link the first space to the map. 
- Link the second space to Help for candidates and committee: https://www.fec.gov/help-candidates-and-committees/
- Link the third space to Legal resources: https://www.fec.gov/legal-resources/

Notify @JonellaCulmer if you need any design files

### Completion criteria
- [ ] Homepage is updated to match the mockup and link to the appropriate pages.

### Design
Screen Shot 2020-02-12 at 1 02 02 PM

### LINKED ISSUE #3585: Update homepage banner image
**What we're after:**
We need to update the homepage image with the new image. Ensure that the image file size is optimized.

New image: 
Homepage_hero_image_flag

Image here: https://drive.google.com/drive/folders/1dfW-I4dJtlrBfucxNycBFS7exQafI5wj

### Related issues
- https://github.com/fecgov/fec-cms/issues/3183 New homepage banner image

### Completion criteria
- [ ] Add the new hero image to the homepage. On mobile/tablet widths, make sure that the flag remains visible.
- [ ] Homepage needs to load at the same time or faster than it does now

### PR DESCRIPTION
**Pull request by johnnyporkchops**
## Summary
- Add new icon links to homepage. Use `.grid__item--with-icon` classes with some additions for  homepage-specific design.
- Make this section of homepage editable in wagtail 
- Add new homepage banner

- [ ]  After merge, do steps 4 and 5 in How-to-test, in production.

@JonellaCulmer : In terms of making the line breaks match the mockup: This is the closest I could get. There are some  imperfect techniques for controlling the line-breaks (like wrapping in spans or adding non-breaking spaces (`&nbsp;`)) but these don't really work with this layout, break at responsive sized and require cluttering the element with  extraneous, non-semantic tags. One good thing with the current layout is that the bottom of each of the three items, lines up symmetrically. But we can go over this further.

- Resolves #3544
- Resolves #3585

## Impacted areas of the application
	modified:   fec/static/scss/layout/_grid.scss
	modified:   home/templates/home/home_page.html

	new file: fec/static/img/i-complex--legal--gray-lightest.svg
	new file: fec/static/img/i-complex--regreport--gray-lightest.svg
        new file: fec/static/img/map-chart-icon.svg

## Screenshots
Screen Shot 2020-03-08 at 10 05 40 PM

## How to test
1)  checkout `feature/3544-add-new-homepage-icon-links`
2)  `npm run build-sass`
3)   Open homepage for editing in Wagtail.
4)  Add the  html below into an `html-block` in `body`
5)  Preview or publish page to see new icon links and banner image
6)  Test links go to right place
```
<ul class="grid grid--3-wide grid--flex u-padding--bottom">
  <li class="grid__item grid__item--with-icon icon--large grid__icon--white text-centered">
    <img src="/static/img/map-chart-icon.svg" alt="icon representing Presidential candidate map">
    <h2 class="u-margin--top"><a href="/data/candidates/president/presidential-map/">Presidential candidate map</a></h2>
    <p>Search presidential data such as money raised, money spent, cash on hand and debt.</p>
  </li>
  <li class="grid__item grid__item--with-icon icon--large grid__icon--white text-centered">
    <img src="/static/img/i-complex--regreport--gray-lightest.svg" alt="icon representing help for candidates and committees">
    <h2 class="u-margin--top"><a href="/help-candidates-and-committees/">Help for candidates and committees</a></h2>
    <p>Help for individuals and groups who are active in federal elections.</p>
  </li>
  <li class="grid__item grid__item--with-icon icon--large grid__icon--white text-centered">
    <img src="/static/img/i-complex--legal--gray-lightest.svg" alt="icon representing legal resources search">
    <h2 class="u-margin--top"><a href="/legal-resources/">Research legal resources</a></h2>
    <p>Explore relevant statutes, regulations, Commission actions and court cases.</p>
  </li>
</ul>

```
- [ ]  After merge, do steps 4 and 5 in How-to-test, in production.

____

### CODE REVIEW

**Comment by pkfec** [comment]
@JonellaCulmer  Can you review @johnnyporkchops when you get a chance?

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Is this under a feature flag? In case we want to go ahead and push this out before the map and stuff are officially ready.

**Comment by johnnyporkchops** [comment]
> @johnnyporkchops Is this under a feature flag? In case we want to go ahead and push this out before the map and stuff are officially ready.
Its not under feature flag.I could  put the name it under same flag as the map. But since its part of the map epic, there's  no reason tp merge it before the map

**Comment by JonellaCulmer** [comment]
If you don't think it's necessary, I defer to you. Thanks, @johnnyporkchops

**Comment by JonellaCulmer** [comment]
Actually, so is the H4CC icon image too. Eeeeeever so slightly

Screen Shot 2020-03-06 at 12 11 46 PM

**Comment by johnnyporkchops** [comment]
@jonella, Good eye. Yes,  SVG seems to default to the centering the 2px border  over the edge of the circle...so 1px of it shows through to the circle underneath and 1px shows through to the white page background. I noticed this too and tried to fix in the SVG but could not. I also though it was not noticeable unless zoomed in, but apparently it is.  
- I will  take another pass at it 
OR 
- We can use a non-transparent (opaque) border at a lighter gray value that achieves the same effect

**Comment by johnnyporkchops** [comment]
@JonellaCulmer . The borders have been corrected for color and clip.

**Comment by pkfec** [comment]
thanks @johnnyporkchops for rebasing your feature branch with develop. I see circle build went thru after your rebase.

**Pull request merged**
