### PR TITLE
AF canonical page updates

### LINKED ISSUE #4552: [Research] Front-end solutions for AF pages and document next steps
**What we're after:**
We have several improvements that need to be made to the AF pages. First we need to research and determine if these changes can be made. We need to document the feasibility and research and make recommendations on what can be accomplished now (and how) and what can't be done now (and why not).

**Action items/considerations:**
- Can we accurately and consistently replace the acronym RTB with Reason to believe?
- Can we accurately and consistently replace the penalty paid flag of Yes/No/Pending with paid/not yet paid/partially paid?
- Document any API necessary changes

### Related issues
- https://github.com/fecgov/fec-cms/issues/4446 Reach out to AF team to kickstart migration

### Completion criteria
- [ ] Document research and findings about the feasibility of the aforementioned considerations, including:
  - Consistently replace acronym "RTB" and display as "Reason to believe"
  - Replace penalty paid flag of Yes/No/Pending with paid/not paid/partially paid
- [ ] Open followup implementation tickets, as appropriate

### LINKED ISSUE #4650: Add additional Administrative fine parameters
### Summary

**What we're after:**
_The last 3 parameters that are needed for the administrative fine work are: `af_dispositions.disposition_description`, `af_dispositions.amount`, `af_dispositions.disposition_date`, `civil_penalty_due_date`, `civil_penalty_payment_status`._

### Related issues

_List any relevant related issue(s)_

- WIP PR: https://github.com/fecgov/fec-cms/pull/4598
- [x] https://github.com/fecgov/openFEC/issues/4832
- [x] https://github.com/fecgov/fec-cms/issues/4552

### Completion criteria

These 3 parameters are added to the Administrative fines canonical page:
- [x] af_dispositions.disposition_description
- [x] af_dispositions.amount
- [x] af_dispositions.disposition_date
- [x] civil_penalty_due_date
- [x] civil_penalty_payment_status

### LINKED ISSUE #4832: Transition inventory meeting (innovation)
### Summary

Looks like the last meeting we held was in 15.3

### Related issues
#4618 

### Completion criteria

- [x] Meeting is held with content and front end to go over the inventory list picking up with /law/crew_152038.shtml
- [x] Spreadsheet updated to reflect meeting
- [x] Redirect ticket created
- [x] Take down ticket created
- [x] Testing ticket

### Future work

Will need to test redirects and put them in take down ticket too.

### PR DESCRIPTION
**Pull request by patphongs**
## Summary

- Resolves #4552 
- Resolves #4650 

Incorporates requested changes for the admin fine canonical pages

## Screenshots

Canonical page with no data for the disposition table

Screen Shot 2021-07-12 at 11 29 54 AM

Canonical page with data for the disposition table

Screen Shot 2021-07-12 at 11 29 24 AM

### Required reviewers

1 UX, 1 front end, 1 backend

## Impacted areas of the application

General components of the application that this PR will affect:

-  Admin fines canonical page

## How to test

- Checkout this branch
- Set your `FEC_API_URL` to the stage environment
- `npm run build` just in case
- `./manage.py runserver`
- Go to an AF canonical page. Ex: http://localhost:8000/data/legal/administrative-fine/26/, http://localhost:8000/data/legal/administrative-fine/3926/
   - Each section should appear: Summary, Disposition, Documents
   - Header should contain the AF number, committee name, and ID
   - Document links should go to the appropriate file on the S3 bucket. Note that the doc links only work for production, since it's a relative path in the code, so this relative path `/files/legal/admin_fines/26/21092501276.pdf` is this in prod: https://www.fec.gov/files/legal/admin_fines/26/21092501276.pdf

### CODE REVIEW

**Comment by JonellaCulmer** [comment]
@patphongs Everything looks good to me, just a couple of comments on the Summary. Can we reduce the space between the two columns, cutting it in half, and the same for the line spacing. I don't think we need that much padding.

**Comment by patphongs** [comment]
> Everything looks good to me, just a couple of comments on the Summary. Can we reduce the space between the two columns, cutting it in half, and the same for the line spacing. I don't think we need that much padding.

@JonellaCulmer I've reduced the line height as well as used the `usa-width-two-thirds` width styles to cut the column widths. Is this better?

Screen Shot 2021-07-12 at 11 18 26 AM

**Comment by patphongs** [comment]
@JonellaCulmer I have put in the extra logic addition requested by AF: Don't show civil penalty due date field if assessed civil penalty is $0.00.

**Review by lbeaufort — APPROVED** [review]
Thanks for your work on this, @patphongs!

**Comment by johnnyporkchops** [comment]
@patphongs Can you add more context of what to be looking  for in the How -To-Test?

**Comment by patphongs** [comment]
> Can you add more context of what to be looking for in the How -To-Test? Even If it's just a couple of examples, I find that helps, even though one can/should read the issue and PR summary.

@johnnyporkchops I added a few things to check for in the How to test section

**Comment by JonellaCulmer** [comment]
@patphongs Only two things:
1. The padding/margin between the committee name and ID and divider line is a bit large. Can we cut that in half? I believe there's a padding and a margin there, each 10 px. 
2. While Robert has been working on the snapshot, he's removed the | after the committee ID on committee profile pages. It's also absent on the candidate profile pages. Can you remove that last bar after the committee ID here too?

**Comment by patphongs** [comment]
@JonellaCulmer The extra spacing for the header and horizontal dividing line has been removed. Also, there is now vertical divider for the last item, committee ID. Could you please re-check?

Screen Shot 2021-08-09 at 11 19 16 AM

**Comment by johnnyporkchops** [comment]
@pat. just two comments. 
- I happened to view this in Opera browser and saw weird entity symbols, similar to what we saw inn court case migration
Screen Shot 2021-08-09 at 11 09 57 AM
- Do we definitely want the URL to be data/legal, or should  we re route it like we didi for audit-search?

https://github.com/fecgov/fec-cms/blob/dc54869e6922cf7713f179a1b3d5b8fdd06e827f/fec/data/views_datatables.py#L124

**Comment by patphongs** [comment]
> * I happened to view this in Opera browser and saw weird entity symbols, similar to what we saw inn court case migration

So those entity symbols persisted from data we got from our internal systems. But now we are not displaying the the disposition text anymore, just the table. So if you do a fresh pull, you should not see that disposition text.

> - Do we definitely want the URL to be data/legal, or should we re route it in `urls.py` like we didi for audit-search? (Maybe for a followup ticket, if yes)

Let's consider this in a follow-up ticket, currently all of the legal searches are within the `/data/legal/` path and we should probably retain the same path for now.

**Review by johnnyporkchops — APPROVED** [review]
Looks good!

**Comment by JonellaCulmer** [comment]
@patphongs From your screenshot it appears the text has changed to gandhi instead of karla. 

> @JonellaCulmer The extra spacing for the header and horizontal dividing line has been removed. Also, there is now vertical divider for the last item, committee ID. Could you please re-check?
> 
> Screen Shot 2021-08-09 at 11 19 16 AM

**Comment by patphongs** [comment]
> From your screenshot it appears the text (committee name and ID) has changed to gandhi instead of karla.

@JonellaCulmer I've fixed it so the font is now using the karla sans-serif font.

Screen Shot 2021-08-09 at 2 16 47 PM

**Comment by JonellaCulmer** [comment]
@patphongs I really hate to do this, but the committee name and ID are not bold and they should be.

**Comment by patphongs** [comment]
@JonellaCulmer The committee name and ID have been bolded

Screen Shot 2021-08-09 at 2 59 51 PM

**Review by JonellaCulmer — APPROVED** [review]
Thanks for all the last minute changes, @patphongs. Looks good.

**Pull request merged**
