### PR TITLE
Independent expenditures datatable: add current version filter and version status

### LINKED ISSUE #3011: [RAW IEs] Implement changes to flyout and filter panel for Raw IEs
**What we're after:** As part of our work to allow users to filter and view transactions that are the latest version, we need to implement several changes to the front end filter and flyout panels on the IE datatable. 

As part of this work, we need to make changes to both the IE datatable Raw AND Processed panels. The work in this ticket contains changes to the Raw filter panel. [Processed IE work happening here.](https://github.com/fecgov/fec-cms/issues/3370)

**Completion criteria:**
Filter panel
- [ ] ~Modify the Regularly Scheduled Report Form to gray out when the 24- and 48-hour reports toggle is active~ This has been moved to a new issue for filter & tags interaction work: https://github.com/fecgov/fec-cms/issues/3448
- [x] Update the Raw filter panel according to the mockup below, including several new filters being added
- [x] Link below version filter is a pop-up similar to other methodology pop-ups
- [x] Update methodology text according to this issue for methodology: https://github.com/fecgov/fec-cms/issues/3360
- [x] Current version filter should be checked by default on page load

Flyout panel
- [x] Change "Open original image" to "Open image" 
- [x] Update the flyout panel according to the mockup below to include version type

#### Flyout panel
Screen Shot 2019-11-18 at 8 45 40 AM

#### Raw filter panel
Screen Shot 2019-11-18 at 8 19 12 AM

### Methodology pop-up
TBD

### PR DESCRIPTION
**Pull request by patphongs**
## Summary (required)

- Resolves #3011 
_For the independent expenditures datatable, this adds the current version filter to filter panel and filing version status to flyout panel for raw and processed data._

**Note:** This PR contains additional code for other raw filing filters. Those filing filters are under the FEC_FEATURE_IE_RAW_FILTERS feature flag. There is an accordion bug that is slated to be worked on next sprint, so those additional filters won't be turned on until that bug has been fixed.

## Impacted areas of the application
List general components of the application that this PR will affect:

-  Independent expenditure raw and processed filings

### Current version filter panel
Screen Shot 2020-01-17 at 2 14 48 PM

### Version methodology modal
Screen Shot 2020-01-17 at 2 14 58 PM

### Version status in flyout panel
Below shows what past version and current version icons look like. I could not find any unknown version to make a screenshot for, but I use the same JS helpers logic as the filings datatable for this, so it should show unknown as the Version if it is unknown.

Screen Shot 2020-01-17 at 2 02 17 PM
Screen Shot 2020-01-17 at 2 01 33 PM

## How to test
- [ ] checkout, npm run build, ./manage.py runserver
- [ ] Go to the [Independent Expenditures datatable](http://localhost:8000/data/independent-expenditures/)
- [ ] Check that the Version filter has been added to both processed and raw data
- [ ] Ensure that the Current version filter is checked by default on load
- [ ] Click on the version methodology modal and ensure the text displays with approved language here: https://github.com/fecgov/fec-cms/issues/3360#issuecomment-575743044
- [ ] Check random filing rows to see if the Version shows up with the correct version status and icons

**Update:** Additionally,
- [ ] Check that the modal doesn't stack under the site header (if the site header is visible at all)
- [ ] Check that other modals aren't affected if they're on the page with the `#version-methodology-modal_processed` modal
____

### CODE REVIEW

**Comment by rfultz** [comment]
**UPDATE:**
Pat found an issue where the depth orders weren't behaving correctly and the overlay was behind the site header:

Until we can write the modal into the page in another way, I've added a line to re-parent the modal element to the <body>, pulling it out from the rule inheritance of the filters panel and letting it stack properly. Doing so, triggered the default site header to hide itself as it does elsewhere on the site. (Not sure I like _that_ but it's consistent with the way the rest of the site works)

Before:
image

After:
image

Going to update How to Test to include this part

**Comment by JonellaCulmer** [comment]
I've checked everything listed under **How to test** including the new work that @rfultz added for the modal stacking. Everything looks good with one exception. Approving without requiring a fix at this time. 

This is work that will need to be included when we work on the toggle/form 24 work this sprint.:
Screen Shot 2020-01-21 at 4 17 27 PM

**Comment by JonellaCulmer** [comment]
@rfultz, @patphongs wanted me to pass along that the modal fix you implemented only seems to work on Processed. I checked and I see the same thing. Sorry I missed that yesterday. Do you mind adding the same fix on the processed modal to raw as well?

**Comment by rfultz** [comment]
Added @johnnyporkchops as a reviewer since I'm now a contributor

**Comment by rfultz** [comment]
@JonellaCulmer I don't want to hold up this release, but this looks weird. Add another ticket? Skip it?
image
(left alignment of "Version methodology" and its icon, and that the item gets a single bottom border instead of an underline)

**Comment by JonellaCulmer** [comment]
> @JonellaCulmer I don't want to hold up this release, but this looks weird. Add another ticket? Skip it?
> (left alignment of "Version methodology" and its icon, and that the item gets a single bottom border instead of an underline)

@rfultz When does this occur?

**Comment by rfultz** [comment]
> > @JonellaCulmer I don't want to hold up this release, but this looks weird. Add another ticket? Skip it?
> > (left alignment of "Version methodology" and its icon, and that the item gets a single bottom border instead of an underline)
> 
> @rfultz When does this occur?

Around the tablet widths

**Comment by rfultz** [comment]
> @rfultz, @patphongs wanted me to pass along that the modal fix you implemented only seems to work on Processed. I checked and I see the same thing. Sorry I missed that yesterday. Do you mind adding the fix on the processed modal to raw as well?

@JonellaCulmer, this is ready for your review and approval

**Comment by JonellaCulmer** [comment]
Looks good. I've already approved. Think we should open up a separate issue to fix the wrapping that @rfultz pointed out. Do you mind opening up a new ticket, @rfultz?

**Pull request merged**
