### PR TITLE
upgrade to django@1.11.23

### LINKED ISSUE #3023: [Med] Snyk - Man-in-the-Middle - django  (due 9/1/19)
Man-in-the-Middle (MitM)
Vulnerable module: django
Introduced through: django-libsass@0.7, django-jinja@2.4.1 and others
Detailed paths
Introduced through: project@0.0.0 › django-libsass@0.7 › django-compressor@2.3 › django-appconf@1.0.3 › django@1.11.20
Introduced through: project@0.0.0 › django-jinja@2.4.1 › django@1.11.20
Introduced through: project@0.0.0 › cg-django-uaa@1.3.0 › django@1.11.20
Introduced through: project@0.0.0 › django@1.11.20

Remediation
Upgrade django to version 1.11.22, 2.1.10, 2.2.3 or higher.

https://app.snyk.io/vuln/SNYK-PYTHON-DJANGO-451300

**To do**
- [ ] Be sure to check Wagtail dependencies and which version of Django it's compatible with.
- [ ] Test on Wagtail CMS to make sure Django upgrade didn't break Wagtail features or any other CMS features.

### PR DESCRIPTION
**Pull request by jason-upchurch**
## Summary (required)

- Resolves #3023 and #2944 
- Update `requirements.txt` from `django@1.11.20`-->~`django@1.11.22`~ `django@1.11.23`

## Impacted areas of the application
List general components of the application that this PR will affect:

-  cms, wagtail

## How to test
- [ ] checkout this branch
- [ ] `pip install -r requirements.txt`
- [ ] run local api / local cms
- [ ] `pytest`
- [ ] review wagtail to ensure behavior is as expected

### CODE REVIEW

**Comment by jason-upchurch** [comment]
> Approved from Wagtail user point of view. I tested on feature and was able to operate Wagtail normally in terms of creating pages, using the different templates and routine tasks like editing, copying and unpublishing pages. No errors were observed.

Thank you @dorothyyeager! As discussed, the wrong branch was pushed to `feature` space. I appreciate your time and help with this, and sorry for the duplication of effort! Please let me know if you find any issues!

**Comment by jason-upchurch** [comment]
Upgrade to `django@1.11.22` introduces 4 new medium severity vulnerabilities:

```
✗ Medium severity vulnerability found in django
  Description: Denial of Service (Memory Exhaustion)
  Info: https://snyk.io/vuln/SNYK-PYTHON-DJANGO-456540
  Introduced through: django@1.11.22, cg-django-uaa@1.3.0, django-jinja@2.4.1, django-libsass@0.7
  From: django@1.11.22
  From: cg-django-uaa@1.3.0 > django@1.11.22
  From: django-jinja@2.4.1 > django@1.11.22

✗ Medium severity vulnerability found in django
  Description: Denial of Service (DoS)
  Info: https://snyk.io/vuln/SNYK-PYTHON-DJANGO-456541
  Introduced through: django@1.11.22, cg-django-uaa@1.3.0, django-jinja@2.4.1, django-libsass@0.7
  From: django@1.11.22
  From: cg-django-uaa@1.3.0 > django@1.11.22
  From: django-jinja@2.4.1 > django@1.11.22
  and 1 more...

✗ Medium severity vulnerability found in django
  Description: Denial of Service (DoS)
  Info: https://snyk.io/vuln/SNYK-PYTHON-DJANGO-456542
  Introduced through: django@1.11.22, cg-django-uaa@1.3.0, django-jinja@2.4.1, django-libsass@0.7
  From: django@1.11.22
  From: cg-django-uaa@1.3.0 > django@1.11.22
  From: django-jinja@2.4.1 > django@1.11.22

✗ Medium severity vulnerability found in django
  Description: SQL Injection
  Info: https://snyk.io/vuln/SNYK-PYTHON-DJANGO-456566
  Introduced through: django@1.11.22, cg-django-uaa@1.3.0, django-jinja@2.4.1, django-libsass@0.7
  From: django@1.11.22
  From: cg-django-uaa@1.3.0 > django@1.11.22
  From: django-jinja@2.4.1 > django@1.11.22
```

Will upgrade under this PR to `django@1.11.23`

**Comment by dorothyyeager** [comment]
An update on my comment. Collection pages use "related page" differently than other templates. On collection pages, the "related pages" appear on the right as "Read next"

Here's what it should look like:

image

In my test in feature, I designated some pages as "related pages" on a test of collection page template, but they didn't render at all.

image

This is something we'd want to ensure works on prod.

**Comment by jason-upchurch** [comment]
> nt to ensur

@dorothyyeager thank you for testing! Can you confirm that on production, you are able to designate some pages as "related pages" on a test of collection page template, and verify that they render as expected? (Maybe this is not possible or desirable, but I'd like to see if the "expected" behavior is currently in place--my thinking is that the minor version upgrade of `django` should not have broken the ability. Thank you!

**Comment by dorothyyeager** [comment]
@jason-upchurch @patphongs I was able to get the collection page template to render correctly in prod and it helped me figure out what I was doing wrong with my test page in feature. (I had neglected to fill in one field.) This template is working correctly after all and was not affected by the upgrade. Sorry for the false alarm and I am able to say, yes, approved from Wagtail user viewpoint.

**Pull request merged**
