### PR TITLE
Adding redistrict text and logic for 2018 PA house districts

### LINKED ISSUE #1997: Add redistricting language to all Pennsylvania House election pages and the election search page
**What we're after:** Pennsylvania has undergone redistricting. We need to alert users to the new districts and explain how we're identifying candidates in those districts. The new language is hammered out, now we just need to deploy it on the pages identified below.

History: https://github.com/fecgov/fec-cms/issues/1959

**Redistricting text:**
> On February 19, 2018, Pennsylvania's Supreme Court released a new congressional map for Pennsylvania. Some candidates subsequently amended their registration forms to reflect new district numbers. Candidates are listed using information from their registration forms and may be running in different districts than in the past.

**Designs:**
**Election search page:** 
screen shot 2018-05-18 at 3 32 13 pm

**Pennsylvania election profile pages:**
screen shot 2018-05-18 at 3 36 06 pm

**Completion criteria:**
- [x] Add text/accordion to search results for all **2017-2018 Pennsylvania** elections. https://www.fec.gov/data/elections/?cycle=2018&state=PA&sort=district
- [x] Add text/informational message to all **2017-2018 Pennsylvania House** election profile pages
https://www.fec.gov/data/elections/house/PA/01/2018/
https://www.fec.gov/data/elections/house/PA/02/2018/
https://www.fec.gov/data/elections/house/PA/03/2018/
https://www.fec.gov/data/elections/house/PA/04/2018/
https://www.fec.gov/data/elections/house/PA/05/2018/
https://www.fec.gov/data/elections/house/PA/06/2018/
https://www.fec.gov/data/elections/house/PA/07/2018/
https://www.fec.gov/data/elections/house/PA/08/2018/ 
https://www.fec.gov/data/elections/house/PA/09/2018/
https://www.fec.gov/data/elections/house/PA/10/2018/
https://www.fec.gov/data/elections/house/PA/11/2018/
https://www.fec.gov/data/elections/house/PA/12/2018/
https://www.fec.gov/data/elections/house/PA/13/2018/
https://www.fec.gov/data/elections/house/PA/14/2018/
https://www.fec.gov/data/elections/house/PA/15/2018/
https://www.fec.gov/data/elections/house/PA/16/2018/
https://www.fec.gov/data/elections/house/PA/17/2018/
https://www.fec.gov/data/elections/house/PA/18/2018/
- [x] Move text from results text to beneath map image for all elections, regardless of selected state, or if no state is selected: "District maps on this page are approximate."

### PR DESCRIPTION
**Pull request by patphongs**
## Summary

- Resolves #1997 
_This adds redistricting language as specified in issue #1997._

When reviewing this PR, make sure that all completion criteria within #1997 are addressed correctly.

## Impacted areas of the application
List general components of the application that this PR will affect:

- Election look up page
- PA district pages

## Screenshots
screen shot 2018-07-27 at 5 00 03 pm

screen shot 2018-07-27 at 4 56 57 pm

### CODE REVIEW

**Comment by JonellaCulmer** [comment]
@patphongs Upon refreshing the page, the Information accordion disappears. In order for it to appear again, I have to start over. Either opening the election search page again, removing the PA information from the URL (`&state=PA&sort=district`) or selecting a different state and then selecting Pennsylvania again, in order to see the accordion again. 

Also, we should not see the informational message on all previous elections. We should only see it on the 2017-2018 election pages.

**Comment by patphongs** [comment]
@JonellaCulmer Nice catches, I've made the changes so that on page refresh the PA redistricting message stays and added the 2018 condition to the PA house pages and election look up page.

**Comment by JonellaCulmer** [comment]
@patphongs I see that the messages and accordion are now gone for elections other than those in 2017-2018 which is great. 

Having an issue with going back to the election search page. After looking at an election profile page in Pennsylvania, then hit the back button, the page is now blank. I have to hit the search button to get information to pop back up on the page. 
screen shot 2018-07-31 at 2 51 19 pm

Also, when I use the `Find another election` feature on an election profile page and select the State and district, I'm taken to the election search page (which is consistent with what's on production) but the accordion is not present.

**Comment by johnnyporkchops** [comment]
@patphongs, @JonellaCulmer:  If I just search PA and do not choose a district, the 2018 district results are in the list but the accordion is not there, should it be?

**Comment by JonellaCulmer** [comment]
@patphongs 
screen shot 2018-07-31 at 3 24 27 pm

**Comment by patphongs** [comment]
@JonellaCulmer here's my responses to your comments:

> Having an issue with going back to the election search page. After looking at an election profile page in Pennsylvania, then hit the back button, the page is now blank.

I don't see this issue when I hit the back bottom. Can you try refreshing and try again?

> when I use the Find another election feature on an election profile page and select the State and district, I'm taken to the election search page (which is consistent with what's on production) but the accordion is not present.

I updated the search function to be consistent on the election profile page as well

> Results page showing cycle

I accidentally added this print statement, this has been removed.

**Pull request merged**
