### PR TITLE
Updating title for MUR searches 

### LINKED ISSUE #3083: Implement "closed cases only" message on MUR search page
### Summary

**What we are after:**
We need to let users of the MUR search know that it doesn't include open and ongoing cases, but only closed ones.

### Related issues

_List any relevant related issue(s)_
- #2969 
- #3049 

### Completion criteria

- [ ] Change label on MUR Search page https://www.fec.gov/data/legal/search/enforcement/?case_no= to read "Closed Matters Under Review" instead of "Matters under review."
- [ ] Add "closed" to the first sentence in the info message at the top that explains what's in our search, so that it reads:

> The MUR search feature includes all closed cases dating back to . . .

- [ ] Include content team member in the PR review for proofreading.

### PR DESCRIPTION
**Pull request by kathycarothers**
## Summary (required)

- Resolves #3083 
_Adds `closed` text to all references of MURs or Matters under review._

## Impacted areas of the application
List general components of the application that this PR will affect:

- Help for candidates and committees landing page
- Legal resources landing page
- MURs search page
- Legal search results page (MUR category, description, and left nav)
- Global legal search options
- MUR search box on enforcement page

#### Help for candidates and committees landing page - http://localhost:8000/help-candidates-and-committees/ 
Screen Shot 2019-09-20 at 9 13 29 AM

#### Legal resources landing page - http://localhost:8000/legal-resources/
Screen Shot 2019-09-20 at 9 14 12 AM

#### MUR search page - http://localhost:8000/data/legal/search/enforcement/
Screen Shot 2019-09-20 at 10 15 09 AM

#### Global legal search options on results page (upper right hand corner) - http://localhost:8000/data/legal/search/?search_type=all&search=%22personal+loans%22
Screen Shot 2019-09-20 at 9 15 48 AM

#### Legal search results page (MUR category, description, and left nav) - http://localhost:8000/data/legal/search/?search_type=all&search=%22personal+loans%22
Screen Shot 2019-09-20 at 9 29 20 AM

#### MUR search box on enforcement landing page - http://localhost:8000/legal-resources/enforcement/
Screen Shot 2019-09-20 at 9 19 59 AM

#### meta tag description for social media related links
Screen Shot 2019-09-20 at 9 21 22 AM
Screen Shot 2019-09-18 at 11 34 50 PM

## How to test
- ./manage.py runserver
- Look at screenshots above and click on localhost links to make sure changes match screenshots
- For content staff - check that the screenshots are ok and that casing for changes are correct

Screen Shot 2019-09-20 at 9 13 29 AM

### CODE REVIEW

**Comment by patphongs** [comment]
> Line 2 , meta-tags.jinja: Make "Closed" lower case (Matters Under Review is fine as is.)
> Line 44, mur_searc.html: Revise to say "closed FEC MURs"
> Line 144, services_landing_page.html: Upper case Matters Under Review
> Line 3, legal-search-results-murs.jinja: Add (MURs) so it reads "Closed Matters Under Review (MURs)"
> Line 58, legal-search-results-murs.jinja: Revise to say "closed FEC MURs"
> Line 97, legal-search-results.jinja: Revise to say "closed FEC MURs"
> Line 82, macros/legal.jinja: Revise to say "closed Matters Under Review"

@dorothyyeager I have made the updates as you have requested and updated the screenshots at the top of this PR. Can you please recheck to make sure things are good?

**Comment by JonellaCulmer** [comment]
@patphongs For the links on the legal landing page, can we reduce the line height between the two lines that MURS now spans? It appears to be 1.8 throughout the page, but in this instance it looks like two separate links instead of one. Can we try 1.4? I'd like to fix this in other places too, such as the "You might also like section" on the H4CC landing page. But I will open a separate ticket for that work since it involves multiple links, not sure for MURs.

The dropdown on the legal search (top-right corner) that has closed lowercase looks real weird. If it's the beginning of the phrase or category, it should be capitalized, right? cc: @dorothyyeager 

Everything else looks good to me!

**Comment by dorothyyeager** [comment]
Oops, good catch @JonellaCulmer - @patphongs, she's right, that particular one should be a capital C. Sorry I missed it! This is the one we're talking about...
image

**Comment by patphongs** [comment]
Thanks @dorothyyeager, the change has been made

Screen Shot 2019-09-20 at 1 11 42 PM

**Comment by dorothyyeager** [comment]
Looks good, @patphongs

**Pull request merged**
