### PR TITLE
Makes POV consistent, Augments contact info

### PR DESCRIPTION
**Pull request by emileighoutlaw**
We're moving away from the first-person POV on this site. This PR removes the "us" from "Contact us" for consistency.

Additionally adds office contact information, based on feedback from Greg Scott.

Content only change. Anyone can review!

### CODE REVIEW

**Comment by noahmanger** [comment]
Should we also be changing the url to `contact` rather than `contact-us`?

**Comment by emileighoutlaw** [comment]
Yep. I think we should @noahmanger. I went back in and changed all the `/contact-us/` links to `/contact/`, but I'm not sure how to change make [the actual contact page](https://github.com/18F/fec-cms/blob/3ffdcc4bf0dfc02aa3225b5fe26adfa208cc2476/fec/home/templates/home/contact.html) be `/contact/` and not `/contact-us/`

**Comment by jenniferthibault** [comment]
@noahmanger your other work reminded me to check in on old PRs. Any idea if we should carry over some of this work or just close it entirely?

**Comment by patphongs** [comment]
This was achieved in this PR: https://github.com/fecgov/fec-cms/pull/2116. This PR is no longer needed.

**Pull request closed without merging**
