### PR TITLE
Update validation style on time period filter

### PR DESCRIPTION
**Pull request by jenniferthibault**
## Summary

While adding the filter validation as a component in the pattern library for https://github.com/fecgov/fec-pattern-library/pull/103 I discovered this instance of the old design using a message component to communicate an error in a filter entry. We've replaced this approach with filter validation styles.

This PR replaces the old approach with the new. 

## Impacted areas of the application
-  The transaction time period filter on the [receipts data table page](https://www.fec.gov/data/receipts/?data_type=processed)

## Screenshots

**Before:**
screen shot 2018-03-30 at 5 55 54 pm

**After:**
screen shot 2018-03-30 at 5 58 15 pm

**Completion criteria:**
- [ ] Determine where the tests are failing and modify accordingly

### CODE REVIEW

**Comment by jenniferthibault** [comment]
@patphongs I could use your good brain here if you're game to review and help fix :) 

What does it mean that the CircleCI tests failed?

**Comment by patphongs** [comment]
Looks like a bunch of js tests are failing @jenniferthibault. These are the failing tests: 

- filter panel should start off closed FAILED
- filter panel should toggle on click FAILED

I'll look more into this

**Comment by jenniferthibault** [comment]
Thank you so much @patphongs !

**Comment by lbeaufort** [comment]
Because this is an older branch, I confirmed that merging `develop` into this branch doesn't solve the failing tests.

**Comment by PaulClark2** [comment]
Closing because it's stale.

**Pull request closed without merging**
