### PR TITLE
Add percent disbursement column per recipient name for committee profile page

### LINKED ISSUE #4962: Add percentage of total disbursements to disbursements table
**What we're after:**
Add the percentage of total disbursements to the disbursements table on the spending tab for PAC profile pages. This will require adding a calculated percentage by vendor compared to total disbursements to the database and API and displaying on the front-end. 

Example: https://www.fec.gov/data/committee/C00727834/?tab=spending&cycle=2020#disbursement-transactions

**Action items:**
- New column for "Percent of total disbursements"
- Update disclaimer language at bottom of table

**Completion criteria:**
- [ ] Calculated percentage has been added to the disbursements table, recipients tab on the spending page for PAC profiles (sorry)

Design:

### PR DESCRIPTION
**Pull request by patphongs**
## Summary (required)

- Resolves #4962 

This adds percent of total disbursements column to the committee profile page.

### Required reviewers

1 UX, 1 front end, 1 back end

## Impacted areas of the application

General components of the application that this PR will affect:

-  Committee profile pages disbursement recipient name tab

### Percent displaying, committee ID C00727834, cycle 2020
Screen Shot 2021-12-02 at 10 21 19 AM

### Null state, committee ID C00000364, cycle 1978
Screen Shot 2021-12-02 at 10 21 45 AM

## Related PRs

Related PRs against other branches:

branch | PR
------ | ------
feature/4988-add-disbursement-percents | [link](https://github.com/fecgov/openFEC/pull/4992)

## How to test

- checkout this branch
- `npm run build`
- `cd fec && ./manage.py runserver`
- Go to any committee profile page disbursements tab. Ex: http://localhost:8000/data/committee/C00727834/?tab=spending&cycle=2020. Click on the group by "Recipient name" tab within disbursements. Check that the "Percent of total disbursements" column is present. 
- Go to a committee profile page with nulls for the percent. Some examples include: C00000364, C00000372, C00000406, C00000554. Make sure that the "Percent of total disbursements" column has "Could not calculate" for its null state.

### CODE REVIEW

**Comment by JonellaCulmer** [comment]
I'm seeing a ton of pages that show "Could not calculate" and I'm just curious if everything is working the way it should.

**Comment by patphongs** [comment]
> I'm seeing a ton of pages that show "Could not calculate" and I'm just curious if everything is working the way it should.

After reviewing with Jonella, percentages seem to be ok. There weren't too many "Could not calculate" percentages.

**Review by JonellaCulmer — APPROVED** [review]
After re-checking, everything works great! Thanks, @patphongs

**Review by lbeaufort — APPROVED** [review]
Great work, @patphongs!

**Review by pkfec — APPROVED** [review]
Looks good @patphongs

**Review by rfultz — APPROVED** [review]
I think it's fine; commented in Slack

**Comment by patphongs** [comment]
> I think it's good; commented in Slack

@rfultz Great catch! For some reason the datatable `orderable` option was set to `false` when it should have been set to `true`. I fixed that in the latest [commit](https://github.com/fecgov/fec-cms/pull/4979/commits/39f07e9083d8dbac10dc9d2ca9ae036ef0197c7f).

**Comment by rfultz** [comment]
Woo hoo!!

**Pull request merged**
