### PR TITLE
Contact page new design and wagtail template

### PR DESCRIPTION
**Pull request by johnnyporkchops**
Implement new design for contact page and make it editable in Wagtail 
New url:  `/contact`

- [x] Requested text file for content of right column (currently has the old content as placeholder text)

- Addresses # https://github.com/fecgov/fec-cms/issues/1943

## Impacted areas of the application
```
modified: fec/static/scss/components/_contact-items.scss
modified: home/blocks.py
new file: home/migrations/0101_auto_20180531_1615.py
modified: home/templates/blocks/contact-info.html
new file: home/templates/home/contact_page.html 
```
## Screenshots
may-09-2018 00-08-52

### CODE REVIEW

**Comment by johnnyporkchops** [comment]
@JonellaCulmer and @dorothyyeager , when you start building the page i wagtail, you might find that you want to leave the `Item label` field blank and just use a headline tag in the rich text area instead, but you can play around with it. Also if any of the required fields cause a problem because you find you want to optionally leave them blank for some cases, I can make them optional.

still

**Comment by JonellaCulmer** [comment]
@johnnyporkchops
@dorothyyeager and I took a look at the template and we have a few tweaks:
First, we'd like to make the item icon optional. This would help for the address section. We don't want to use the same icon twice in a row for both addresses and right now we'd be required to use them both. If they are made optional we can avoid this.

Second, can you rename "Sections" to "Help with sections". It wasn't immediately clear which section we were adding information too and whether we needed to include a header. If you modify that, it would help. Particularly in the future when someone else may need to go in and make edits.

Could you also edit "Help With" to "Help with"?

Linking didn't work in the item info section for internal or external links, but it did for email. These need to be functional, particularly for the Contact your analyst section

Finally, if we could limit the "Help with" section to just one section. I think that will help limit and future modification of the template.

Let me know if you have any thoughts or questions.

**Comment by JonellaCulmer** [comment]
@patphongs I was able to publish a page locally without any errors.

**Comment by johnnyporkchops** [comment]
@JonellaCulmer, @patphongs . Thanks for your reviews. I will take a look at these issues.

**Comment by johnnyporkchops** [comment]
Here is a screenshot of the full contact page built using the template.
contact_full_page_composite

**Comment by dorothyyeager** [comment]
Hi John - looks good. A couple of small fixes to request:
1) Help With - make that "Help with" (lower case w)
2) Information Division should be above its phone number and not bold (following the pattern used for the other divisions)

Thanks!

**Comment by dorothyyeager** [comment]
It's a template (so no need to make my small edit as we'll do that once we make the real page). @JonellaCulmer and I paired with @johnnyporkchops and requested an edit to the "Help with" section - to make a separate, editable, section title in case a wording change is desired in the future. That's been made, and everything else looks good to go, so approving from my end (previewed it on John's local).

**Comment by johnnyporkchops** [comment]
I  cleaned up the migration history for this PR so I am not pushing the history of adding/removing/renaming fields etc to the repo, rather just one migration file that represents the current and final state for this template's model. 
I also paired with @jculmer so se could reset her local database and run this locally with just the one migration.

**Pull request merged**
