### PR TITLE
Add download headshot button to commissioner pages

### LINKED ISSUE #6467: Add download button for Commissioner headshots
### What we're after
Add button to Commissioner bio page templates to download a headshot. 

### Related issues
- https://github.com/fecgov/fec-cms/issues/6381

### Completion criteria
- [ ] Content team can upload images into Commissioner bio page templates in Wagtail
- [ ] Button appears on the front-end IF there is an image to download and doesn't if there isn't one to download
- [ ] Should image opens in a new browser tab or automatically download?
- [ ] Also fix the broken alt tag : `{{ commissioner_title  }}` to `{{ self.title  }}` in the existing img in the template

### Front-end design
Screenshot 2024-08-28 at 1 17 56 PM

### PR DESCRIPTION
**Pull request by johnnyporkchops**
## Summary (required)

- Resolves #6467
- Add `headshot_download` image field to commissioner pages Wagtail template
- Add "Download headshot" button on the page, if a`headshot_download` image has been uploaded
- Include associated migration file for model change
- Tested in Chrome, Firefox, Edge, Safari, Opera, Brave

### Required reviewers

one ux -OR-  one frontend

## Impacted areas of the application

Commissioner pages

## Screenshots

download

## How to test
- checkout branch and  `./manage.py migrate`
- Edit Commissioner Cooksey's page `picture_download`  field and upload this photo (or any photo)  to your local:
 https://www.fec.gov/resources/cms-content/images/Cooksey.original.png
-  Publish or preview the page and click "Download headshot" button
- Remove the image to confirm that the button does not render if there is no image in that field

### CODE REVIEW

**Comment by johnnyporkchops** [comment]
@JonellaCulmer Now there will be a new field named `picuture_download` where editors can upload a photo submitted ;by the commissioner as their downloadable headsshot photo. Do we want the download button to only show if that field is populated with a photo, or do we want the button to default to download the existing circular image for the commissioner if nothing is uploaded to the new field?

**Comment by JonellaCulmer** [comment]
@johnnyporkchops We can just show the image if there's something to download. Hidden if not. Thanks for asking!

**Review by JonellaCulmer — APPROVED** [review]
@johnnyporkchops Looks great, thanks so much! I do see that we still have an appearance issue with our export/download icon. I put a ticket in here to fix: https://github.com/fecgov/fec-cms/issues/6457

Perhaps we can prioritize this for next sprint if it's a 1 pointer? cc: @patphongs

**Review by patphongs — APPROVED** [review]
👍

**Pull request merged**
