### PR TITLE
Feature/4220 node package vulnerabilities

### LINKED ISSUE #4220: NPM audit - Low vulnerabilities
# Summary
We've been accumulating vulnerabilities that `npm audit` has labeled as low and I'd like to address them (currently 67 'low' (plus 8 'high'))

### PR DESCRIPTION
**Pull request by rfultz**
## Summary

- Resolves #4220 

Updating packages that `npm audit fix` could fix with only a patch-level fix.
One of those required an update to the polyfills file.

## Reviewers
Feel free to add or remove—not sure exactly who would _need_ to approve

## Impacted areas of the application

Mostly the build and automated tests but, since JavaScript is involved, it could affect any of the interactive parts of our site, too (datatables, maps, widgets, admin, etc)

## Screenshots

None

## Related PRs

None

## How to test

- Pull the branch like normal
- `npm i` to install updated packages. It should end with at note about (at current) 23 low severity vulnerabilities
- `npm audit` will give you more details if you're interested
- `npm run build` will build and minify the CSS and JavaScript
  - (`npm run build-sass` will build the css
  - `npm run build-js` will build the JavaScript
  - `npm run build` will do both)
- `npm run test-single` will run the tests
- `./manage.py runserver`
- Check that [localhost](http://127.0.0.1:8000/] is working as expected, including
  - homepage
  - datatables pages (including sorting)
  - maps (like on the homepage and 
  - widgets (Aggregate Totals, Where Contributions Come From, Presidential Financial Map, Admin Fines Calculator)

____

### CODE REVIEW

**Review by JonellaCulmer — APPROVED** [review]
Everything looks really great. Didn't check the Where contributions come from because I didn't have the feature flag turned off, I guess. Would appreciate if one of the other reviewers could take a look at that.

**Comment by JonellaCulmer** [comment]
@rfultz I'm not able to see the changes locally. I cannot get to all menu items and the top of the page looks the same to me. Happy to pair with you to show you what I'm seeing.

**Review by johnnyporkchops — APPROVED** [review]
Looks good, tested basic pages and widgetry (agg totals, WCCF, maps)

**Comment by rfultz** [comment]
> @rfultz I'm not able to see the changes locally. I cannot get to all menu items and the top of the page looks the same to me. Happy to pair with you to show you what I'm seeing.

I think this comment was for another ticket

**Pull request merged**
