### PR TITLE
Document type filter and MUR & ADR & AF UI changes v3

### LINKED ISSUE #5259: Build out document type search and update MUR & ADR UI to match
**What we're after:**
The MUR search should support document type search like AO's. We will not be able to use the framework exactly like AOs. 

Endpoint: https://api.open.fec.gov/v1/legal/search/?api_key=DEMO_KEY&type=murs&case_doc_category_id=1

**Related tickets:**
- https://github.com/fecgov/openFEC/issues/5106
- https://github.com/fecgov/openFEC/issues/5119
- https://github.com/fecgov/fec-cms/issues/4801

**Completion criteria:**
- [ ] Researchers can now filter by document type

**Designs:**

### PR DESCRIPTION
**Pull request by patphongs**
## Summary

Resolves #5259 

Specific updates for MURs and ADRs:
- Adds MUR document type categories, filters, and results display
- Adds ADR document type categories, filters, and results display

Search result UI display updates for MURs, ADRs, and Admin Fines:
- Add pagination to top and bottom of results
- Add per page pagination
- Add number of results per page options
- Add filter tags and capability to remove tags
- Add interstitial loading overlay to table

### Required reviewers

1 or 2 front end
1 UX

## Impacted areas of the application

General components of the application that this PR will affect:

- [MUR search](http://localhost:8000/data/legal/search/murs/)
- [ADR search](http://localhost:8000/data/legal/search/adrs/)
- [AF search](http://localhost:8000/data/legal/search/admin_fines/)

## Screenshots
Screenshot 2024-06-05 at 12 49 47 PM

Screenshot 2024-06-05 at 12 50 07 PM

Screenshot 2024-06-05 at 12 50 38 PM

## How to test

This is also still deployed to the stage environment, if you would like to use that instead for testing.

- Test document type filters on: 
   - [MURs](http://localhost:8000/data/legal/search/murs/)
   - [ADRs](http://localhost:8000/data/legal/search/adrs/)
   - [AFs](http://localhost:8000/data/legal/search/admin_fines/)
  
- Test new UI features:
   - Pagination to top and bottom of results
   - Per page pagination
   - Results per page options
   - Filter tags and capability to remove tags
   - Interstitial loading overlay to table

### CODE REVIEW

**Review by johnnyporkchops — APPROVED** [review]
Works good, Great work Pat!

**Review by JonellaCulmer — APPROVED** [review]
Everything looks good to me, Pat. Checked the UI changes on AF, ADRs and MURs and the document type filter on ADRs and MURs and they all seem to work as expected. Would like to add to a future ticket to organize the document type filter like our others with multiple options and pull out the top selections. We can handle it when we look to change the categories.

Ex. committee type filter on receipts datatable
Screenshot 2024-06-10 at 3 16 54 PM

**Review by rfultz — APPROVED** [review]
I can't seem to break it. I created a ticket to add input masks to the date filter fields so users don't need to type the slashes

**Comment by patphongs** [comment]
> Would like to add to a future ticket to organize the document type filter like our others with multiple options and pull out the top selections. We can handle it when we look to change the categories.

Sure @JonellaCulmer, please go ahead and log a future ticket for this work

**Pull request merged**
