### PR TITLE
Upgrade npm to latest

### LINKED ISSUE #4591: Upgrade NPM to 7.24.0(lts)
Before we get too many versions behind, let's get NPM upgraded to the LTS (long-term support) version.

Last time I tried, I got several errors.

Trying again on 2021-05-04, `npm i` is breaking because `draftail` wants `draft-js@^0.10.5` and we're listing `^0.11.7` in `package.json`. Both are requesting `0.x.x` so they seem to be arguing for the sake of arguing

### Completion criteria
NPM has been upgraded to its `@lts` successfully (no errors, no warnings, all `npm run ` scripts work as expected)

### PR DESCRIPTION
**Pull request by pkfec**
## Summary (required)

Upgrade NPM to latest  version 7.24.0

- Resolves #4591

(Include a summary of proposed changes and connect issue below)
- update NPM version in package.json
- generate package-local.json with latest npm changes

### Required reviewers

At least two developers required

## Screenshots

**Before NPM package upgrade**:

```
(cms3710) macadmins-mbp-5:fec-cms pkasireddy$ node -v
v10.16.0
(cms3710) macadmins-mbp-5:fec-cms pkasireddy$ npm -v
6.14.3
```

**After NPM package upgrade**:
```
(cms3710) macadmins-mbp-5:fec pkasireddy$ node -v
v14.13.0
(cms3710) macadmins-mbp-5:fec pkasireddy$ npm -v
7.24.0
```

## How to test

- checkout branch
- create new python virtual env: run `pyenv virtualenv 3.7.10 cms3710` 
- install requirements: run `pip install -r requirements.txt`
- check the local  npm version before upgrade:
    - run `npm -v` : terminal  display `6.14.*`
- remove existing node_modules folder on fec-cms repo: run `rm -rf node-modules`
- clear npm cache: run `npm cache clean -f`
- install/update to latest npm:  run `npm install -g npm@7.24.0`
- verify the npm version: run `npm -v` : terminal display `7.24.0`
- run `python manage.py migrate`, just in case
- run `npm i`
- run `npm run build`
- run `npm run build-sass`, just in case 
- run `npm run build-js`, just in case
- run `npm run test-single`, just in case
- start server and test website  (http://127.0.0.1:8000/): run `./manage.py runserver`
- make sure no errors on browser or the terminal logs

### CODE REVIEW

**Comment by johnnyporkchops** [comment]
@rfultz Do you have any pointers on what to look out for wen testing this based on your pas experience trying to upgrade NPM here: https://github.com/fecgov/fec-cms/issues/4591

**Review by johnnyporkchops — APPROVED** [review]
Works good, found no errors with installs/builds or package performance.

**Comment by johnnyporkchops** [comment]
Found no errors with bump to npm 7.23, my approval stands.

**Comment by rfultz** [comment]
Finally coming back to this after so many issues with upgrading brew, etc.

7.23.0 is no longer the latest npm. `npm i -g npm@latest` gives us 7.24.0; should we just move to that?

Likely outside the scope of this ticket, I'm getting warnings that we need to change `psycopg2==2.8.6` to `psycopg2-binary==2.8.6`. When I do, things seem fine

**Comment by pkfec** [comment]
> Finally coming back to this after so many issues with upgrading brew, etc.
> 
> 7.23.0 is no longer the latest npm. `npm i -g npm@latest` gives us 7.24.0; should we just move to that?
> 
> Likely outside the scope of this ticket, I'm getting warnings that we need to change `psycopg2==2.8.6` to `psycopg2-binary==2.8.6`. When I do, things seem fine


@rfultz Thanks for hanging in there!! It appears NPM version got updated thrice in 2 weeks this month. Lets bump it to the latest version `7.24.0. I will update my instructions above.

We should handle psycopg2 pkg warning in a separate issue. Can you go ahead and open a new issue?

**Comment by pkfec** [comment]
@johnnyporkchops @rfultz I bumped the NPM to the latest version 7.24.0. Please test this PR.

**Review by johnnyporkchops — APPROVED** [review]

**Comment by rfultz** [comment]
Have we tested this on dev/stg? Have we checked which version of npm is being used on stg/dev/etc with or without this change?

The version of npm inside the package file doesn't dictate which version is installed on the server—it's just a note for anyone trying to include our repo in their own. The version of npm is determined by the version of Node, which comes from the CircleCI image. Right?

The newer versions will tell us when there's a mismatch between our installed and 'required' versions but it doesn't fix them.

**Comment by pkfec** [comment]
> Have we tested this on dev/stg? Have we checked which version of npm is being used on stg/dev/etc with or without this change?
> 
> The version of npm inside the package file doesn't dictate which version is installed on the server—it's just a note for anyone trying to include our repo in their own. The version of npm is determined by the version of Node, which comes from the CircleCI image. Right?
> 
> The newer versions will tell us when there's a mismatch between our installed and 'required' versions but it doesn't fix them.

@rfultz I deployed a test branch to `dev` space with the latest NPM changes here:
https://app.circleci.com/pipelines/github/fecgov/fec-cms/1524/workflows/4467c954-5d5a-46f2-84d7-e66c3cc5e189/jobs/4808

**Comment by pkfec** [comment]
@rfultz The circle docker image for Node version 14.13.0  comes with NPM version 6.14.8. I verified that builds running with the docker  image Node/NPM versions and also noticed that the latest NPM  is getting during Install node dependencies task.  
Here are the screenshots:

Screen Shot 2021-09-28 at 1 35 06 PM

Screen Shot 2021-09-28 at 1 47 46 PM

**Comment by rfultz** [comment]
I just saw that. The default is npm 6.14.8, so this PR wouldn't change that. Except there's another line below that mentions npm v7.23.0 (presumably 7.24.0 now).

image


Just want to make sure
# this PR does something (is smart-buffer reading it and that's how we get to 7.2x.0? Otherwise, the `engines` section of package.json is just a note)
# it represents what we're actually requiring/recommending
  - for localhost (controlled by `npm i -g`, not package.json)
  - for non-localhost (controlled by CircleCI (6.14.8?), not package.json)

**Comment by pkfec** [comment]
Are there any technical constraints to approve/merge this PR?

**Review by rfultz — APPROVED** [review]
That we upgraded npm through our global settings, this PR updates the recommendation in the 'engines' section of package.json. (The version of npm on CircleCI is likely different, based on the image and version of Node it includes)

**Pull request merged**
