### PR TITLE
Handle ServiceNow API outage or URL change

### LINKED ISSUE #3718: RAD contact page goes down when servicenow API is down
The RAD contact page goes down when ServiceNow API is down. We should fall back to "look up your analyst" when we can't get to the ServiceNow API

How to test: 

- Set "FEC_FEATURE_RADFORM": true
- Set these, but with bad URL or creds:
     "FEC_SERVICE_NOW_API": 
     "FEC_SERVICE_NOW_PASSWORD":
     "FEC_SERVICE_NOW_USERNAME": 
- Go to http://localhost:8000/help-candidates-and-committees/question-rad/

Example error: 
```
2020-04-27T10:25:32.30-0400 [APP/PROC/WEB/2] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
   2020-04-27T10:25:32.30-0400 [APP/PROC/WEB/2] ERR     response = get_response(request)
   2020-04-27T10:25:32.30-0400 [APP/PROC/WEB/2] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
   2020-04-27T10:25:32.30-0400 [APP/PROC/WEB/2] ERR     response = self.process_exception_by_middleware(e, request)
   2020-04-27T10:25:32.30-0400 [APP/PROC/WEB/2] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
   2020-04-27T10:25:32.30-0400 [APP/PROC/WEB/2] ERR     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   2020-04-27T10:25:32.30-0400 [APP/PROC/WEB/2] ERR   File "/home/vcap/app/fec/home/views.py", line 268, in contact_rad
   2020-04-27T10:25:32.30-0400 [APP/PROC/WEB/2] ERR     form = ContactRAD()
   2020-04-27T10:25:32.30-0400 [APP/PROC/WEB/2] ERR   File "/home/vcap/app/fec/fec/forms.py", line 17, in __init__
   2020-04-27T10:25:32.30-0400 [APP/PROC/WEB/2] ERR     category_options = [('', 'Choose a subject')] + form_categories()
   2020-04-27T10:25:32.30-0400 [APP/PROC/WEB/2] ERR   File "/home/vcap/app/fec/fec/forms.py", line 69, in form_categories
   2020-04-27T10:25:32.30-0400 [APP/PROC/WEB/2] ERR     raw_categories = fetch_categories()
   2020-04-27T10:25:32.30-0400 [APP/PROC/WEB/2] ERR   File "/home/vcap/app/fec/fec/forms.py", line 58, in fetch_categories
   2020-04-27T10:25:32.30-0400 [APP/PROC/WEB/2] ERR     return r.json()['result']
   2020-04-27T10:25:32.30-0400 [APP/PROC/WEB/2] ERR KeyError: 'result'
```

- [ ] Add logging when unable to connect to ServiceNow. Slack alert? How to not send thousands of these? Maybe just a Pingdom alert for servicenow api instead of the contact page itself.

### PR DESCRIPTION
**Pull request by lbeaufort**
## Summary (required)

Resolves #3718

- Handle ServiceNow API outage/URL change by only showing analyst lookup 
- Add test coverage 
- Remove feature flag for RAD form
- Add error message when ServiceNow is unavailable

## Impacted areas of the application

Contact RAD page

## How to test

Include any information that may be helpful to the reviewer(s).

### Reproduce error
- Checkout `develop`
- ~Set `FEC_FEATURE_RADFORM=True`~ removed this env var
- Set these, but with bad URL or creds:
- `FEC_SERVICE_NOW_API`: "https://api.open.fec.gov/" or "https://api.open.fec.gov/v1/committees/?api_key=DEMO_KEY&committee_id=C00431445&page=0" until the server error is fixed, or anything that doesn't have a "results" object
- Go to http://localhost:8000/help-candidates-and-committees/question-rad/
➡️ get error `KeyError: 'result'`
### Verify fix
- Checkout this branch
- ~Set `FEC_FEATURE_RADFORM=True`~ removed this env var
- Set these, but with bad URL or creds:
- `FEC_SERVICE_NOW_API`: "https://api.open.fec.gov/" or "https://api.open.fec.gov/v1/committees/?api_key=DEMO_KEY&committee_id=C00431445&page=0" until the server error is fixed, or anything that doesn't have a "results" object
- Go to http://localhost:8000/help-candidates-and-committees/question-rad/
- Should just see RAD analyst lookup, not question submission form
- Set `FEC_SERVICE_NOW_API`, `FEC_SERVICE_NOW_PASSWORD`, and `FEC_SERVICE_NOW_USERNAME` to the values in a cloud.gov environment
- Contact form should appear with categories. If you test a submission, be sure to let the committee's assigned analyst know that it's a test

### Screenshot
Screen Shot 2020-07-28 at 1 59 02 PM

### CODE REVIEW

**Comment by johnnyporkchops** [comment]
https://github.com/fecgov/fec-cms/blob/84b8462afa30ee0f80ea835f12fb66be367d30ea/fec/home/templates/home/contact-form.html#L83-L84
**Is there any value in putting in an alert where a user is used to seeing the question submission form. We could put:**
```
{% elif not form %}   
    <div class="message message--alt message--alert"><span class=t-note>
     The question submission form is temporatily unavailable, please contact your analayst directly using form above or check back soon<span>
    </div>
```

Screen Shot 2020-07-27 at 1 05 18 AM

**Comment by lbeaufort** [comment]
@fec-jli and @johnnyporkchops thanks for your review, and your suggestion. @johnnyporkchops thanks for the sample code, but I think it would need a tweak - I think it would show that message if the form is turned off with the feature flag. That might be a good argument for removing the feature flag for this. 

I defer to @JonellaCulmer if she wants to add a message if the form is down - for what it's worth, it seems like more helpful behavior to me.

**Comment by JonellaCulmer** [comment]
I think it's a great idea and looks good too, @jun and @johnnyporkchops. 

Suggested language changes: The question submission form is currently unavailable, please contact analysts directly or check back soon.

@dorothyyeager Do you have time to look at my proposed language? I modified to remove "you" word and "above".

**Comment by lbeaufort** [comment]
@JonellaCulmer @dorothyyeager thanks! One thought - in other places we refer to
```
your committee's RAD analyst
your designated analyst
the analyst
your committee's analyst
your campaign finance analyst
an assigned analyst
...etc
```
but not "analysts" so singular might be better than plural.

**Comment by dorothyyeager** [comment]
Thanks @JonellaCulmer Small changes: change comma to semi-colon and add "RAD" but see question below.
The question submission form is currently unavailable; please contact RAD analysts directly or check back soon.

Question: If the form is down, can they still look up a RAD analyst? If so, go with my language above. If not, I'd modify the sentence to take out "contact RAD analysts direct or".

cc'ing @bmathesonFEC who should weigh in because it's the RAD contact form.

**Comment by lbeaufort** [comment]
@dorothyyeager 
>If the form is down, can they still look up a RAD analyst? If so, go with my language above. If not, I'd modify the sentence to take out "contact RAD analysts direct or".

Yes, they can still look up their analyst. I'll wait for @bmathesonFEC to weigh in before making more changes.

**Comment by johnnyporkchops** [comment]
@lbeaufort wrote:
```I think it would show that message if the form is turned off with the feature flag. That might be a good argument for removing the feature flag for this.```
I tested this and you are correct, it shows up when the feature flag is turned off. I suppose we could add, yet more conditional stmts to the many already there to accommodate this scenario as well, or remove  feature flag. Is there a strong use-case for wanting to turn a flag on/off for this feature?

**Comment by lbeaufort** [comment]
> @lbeaufort wrote:
> `I think it would show that message if the form is turned off with the feature flag. That might be a good argument for removing the feature flag for this.`
> I tested this and you are correct, it shows up when the feature flag is turned off. I suppose we could add, yet more conditional stmts to the many already there to accommodate this scenario as well, or remove feature flag. Is there a strong use-case for wanting to turn a flag on/off for this feature?

I removed the feature flag with 291825b87691614d115c97f46f8a5bbe0d785cec because I don't think we need a feature flag for a feature that's been in production for 3 years.

**Comment by johnnyporkchops** [comment]
Thanks @lbeaufort . I we wanted the feature flag at a later date, maybe we could just wrap code in the template in the feature flag, like we do in other templates, since it's not driving view logic anymore.

**Comment by lbeaufort** [comment]
@JonellaCulmer @bmathesonFEC @dorothyyeager I've updated the error message with Brad's suggested language change
Screen Shot 2020-07-28 at 1 59 02 PM


```
The question submission form is currently unavailable; please contact the committee's assigned RAD analyst directly or check back soon.
```

**Pull request merged**
