### PR TITLE
Elections page - fix responsive behavior  and show currency columns in mobile

### LINKED ISSUE #4668: Mobile - Financial totals missing from election profile page
**This issue was transferred from the feedback repository**

 **What we are after**
Users should be able to see some candidate financial information when viewing an [election profile page](https://www.fec.gov/data/elections/senate/WI/2022/ ) on a mobile device.

**Related**
Might be related to https://github.com/fecgov/fec-cms/issues/4656

**Screenshot**
IMG_0010

**Completion criteria**
- [X] Decide what financial information should be displayed (Name and raising total)
- [ ] Make change so user can see financial information (name and raising total)
- [ ] Enter future design ticket to make the table more user friendly

## What were you trying to do and how can we improve it?
 Financial totals on election profile pages missing from mobile view  

## Details
* URL: https://www.fec.gov/data/elections/senate/WI/2022/ 
* User Agent: Amazon CloudFront

### PR DESCRIPTION
**Pull request by johnnyporkchops**
## Summary 
- Adds priority to show  `Total receipts` , `Total disbursements`,  and `Cash on hand` columns in mobile for the first table `Candidate financial totals` in mobile view, issue:  #4668
- Allows obscured rows to be scrolled/swiped to
- Fixes responsive stacking issue on Election and Candidate profile pages, issue:  #4656
  - Committee profile pages stack the tab nav and above the tables at 940px whereas the Election and Candidate proffile pages were not until the size reached @640p cutting off content.
  
 - Quote from issue 4656 that applies to both issues:
   ```
   The display should stack according to screen size and 
   you should also be able to scroll horizontally for the datatables when there's smaller screens.
   
   ```
  
- [ ] Create followup issue : Per the completion criteria, to address overall usability off Election profile page tables and also to address places on Committee profile pages where the most relevant columns are not show in mobile. 
 
 <hr>
 
 -  Resolves #4668 
 - Also resolves issue #4656
 
<hr>

**Note:** At some  screen/device widths, the browser's and dataTables.responsive.js's  built in responsive logic cannot precisely calculate what width to set columns at without the possibility of some partially obscured columns (These columns will be accessible by scrolling/swiping, changing device orientation, or desktop screen resizing) There are many factors at play that determine the nuance of  how a tables columns are sized and hidden/shown:
  - The browsers native column width calculations
  - jQuery `dataTables.responsive.js` calculations
  - jQuery `dataTables.responsive.js` [responsive opts](https://datatables.net/reference/option/autoWidth) and [utility classe](https://datatables.net/extensions/responsive/classes)s that we add to columns in our js.

<hr>

### Required reviewers
one frontend, one UX

## Impacted areas of the application

modified:   fec/static/js/modules/table-columns.js
modified:   fec/static/scss/components/_data-container.scss
modified:  data/templates/elections.jinja
modified:   data/templates/partials/elections/about-this-election-tab.jinja
modified:   data/templates/partials/elections/election-data-and-compliance-tab.jinja

## Screenshots
(This was also tested on a real iphone)
Jul-09-2021 01-04-22

## How to test [4668 ](https://github.com/fecgov/fec-cms/issues/4668)

- checkout `feature/4668-fix-show-receipts-on-mobile-elections`
- `npm run build`
- View an election page like http://127.0.0.1:8000/data/elections/senate/WI/2022/
- Switch to responsive view in inspector
- Choose `iphone 5/SE`(the size that the issue requestor was using)  and see for `Candidate financial totals` table, the  `Total receipts` is now visible instead of the `Party` column
- Swipe left to also see 'Total disbursements`  and `Cash on hand` (this was tested live on real  IPhone too)
- Change orientation to landscape to see all three columns.
- Regarding the partially obscured, but accessible columns you may see in other device sizes, please see "**Note**" above.

## How to test [4656](https://github.com/fecgov/fec-cms/issues/4656)
- Resize screen in desktop view to see that the cards on Election and Candidate profile pages  do not get cut off. 
  - Note: There is a slight overlap on the cards that happens at about 1000px (before it stacks at 940px), but I did not think is was worth having the whole thing stack at such a large breakpoint just to accommodate a slight overlap on a card. 940px seems large as it is. 

Should you desire, you can test it on your real iPhone or Surface using this technique: https://github.com/fecgov/fec-cms/wiki/Testing-a-dev-branch-on-iPhone,-Internet-Explorer-Windows,-Android

### CODE REVIEW

**Review by patphongs — APPROVED** [review]
Works great, thanks @johnnyporkchops!

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Not sure what I'm doing wrong in my review, but I'm seeing the table scroll but the Party column is still second. Viewing the desktop view the table is huge now. 

Screen Shot 2021-07-14 at 4 41 17 PM

Screen Shot 2021-07-14 at 4 40 26 PM

**Comment by johnnyporkchops** [comment]
> @johnnyporkchops Not sure what I'm doing wrong in my review, but I'm seeing the table scroll but the Party column is still second. Viewing the desktop view the table is huge now.

@JonellaCulmer The responsive features for JQuery datatables that we use for showing/hiding columns are Javascript driven so they when you switch between desktop and mobile size (or switch to  responsive inspector) you have to refresh to accurately simulate the behavior of a user loading the site at that size on a mobile device.

The width of the tables for Election pages  now match the width of the similar tables on [Committee](https://www.fec.gov/data/committee/C00137828/?tab=raising) and [Candidate](https://www.fec.gov/data/candidate/H2GA10174/?cycle=2022&election_full=true&tab=raising#individual-contribution-transactions) pages so they adhere to the same breakpoints, are uniform, and take advantage of available space to fit the many columns. 

Let me know if you have any other questions.

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Oh, okay. So you had to change the width of the tables on desktop in order to show the two selected columns on mobile? I wouldn't have figured that would be the case. I'll take another look.

**Comment by johnnyporkchops** [comment]
> @johnnyporkchops Oh, okay. So you had to change the width of the tables on desktop in order to show the two selected columns on mobile? I wouldn't have figured that would be the case. I'll take another look.

I made the width of the tables (or more specifically, the container they are in)  the same as similar tables in Candidate and Committee  pages iso that they are uniform and can adhere to the same breakpoints. That has nothing to do with hiding columns in Mobile. It is more applicable visually in the fix or the other ticket https://github.com/fecgov/fec-cms/issues/4656

**Review by JonellaCulmer — APPROVED** [review]

**Pull request merged**
