### PR TITLE
Feature/meetings page enhancements 2166

### LINKED ISSUE #2166: Improve meeting page template in Wagtail
We've begun streaming open meetings and hearings using YouTube.  In doing this, we've discovered things that need improvement in the meeting page template. This issue replaces #2108, 2095 and 2099.

Background: https://github.com/fecgov/fec-cms/pull/1323, https://github.com/fecgov/fec-cms/issues/2095, https://github.com/fecgov/fec-cms/issues/2099, 

Completion criteria:
- [x] Update template to allow for meetings that last more than one day, so that only one page needs to be created per hearing/meeting
- [x] Add the "hearing" option to the template (which right now only offers a choice between labeling as an open meeting or an executive session). Hearings are open but differ from regular open meetings.
- [x] Add optional block for optional intro text.
- [x] Add the ability to copy/paste the YouTube embed code via html editor or html block into the meeting page template.
- [x]  Make embedded video mobile-responsive.
- [x] Add fields for video links to specific agenda items or testimony within the meeting page. (For routine open meetings, these links will be per agenda item but for hearings they will be per panel.)

Make additional changes requested by Commission Secretary regarding hearing titles and page titles:
- [x] Change the page name from Hearings to Public Hearings (https://www.fec.gov/meetings/?tab=hearings)
- [x] Move all Audit Hearings, Administrative Review Hearings, and Oral Hearings to their chronological order placement on the Open Meeting page, as they appeared on the classic website
- [x] Make pages for missing hearings and update other hearings as requested by Secretary. (Content work)

### PR DESCRIPTION
**Pull request by johnnyporkchops**
Resolves #2166 

This PR includes adding new fields to meeting page wagtail template, adding ability to embed responsive video and changes to how hearings appear on the all-meetings page. I will demo in design sync to get feedback from content group.

## Impacted areas of the application
Meeting page templates, All-meetings index page, CSS, view 
        modified:    fec/static/scss/_icon-variables.scss
	modified:   fec/static/scss/components/_agendas.scss
	modified:   fec/static/scss/components/_icons.scss
	modified:   home/models.py
	modified:   home/templates/home/commission_meetings.html
	modified:   home/templates/home/meeting_page.html
	modified:   home/views.py

## New Fields:
new_fields
<hr>

## Responsive video:
(this only looks blurry because it is compressed)

resp_mtg_vid2

<hr>

## For in-item video links for two-day hearings:

in-item-video_links

## Related PRs
List related PRs against other branches:

<hr>

## How to test: Coming soon

### CODE REVIEW

**Comment by johnnyporkchops** [comment]
@JonellaCulmer, please let me know if the video icon I added will suffice or you think we need something else to better match the vernacular of the audio icon (and others). 
On old meeting pages, we had a video icon, but always wanted to switch it out because it just looks like an arrow.
Old Video Icon example: https://www.fec.gov/updates/august-16-2016-open-meeting/
(Please notice that on the newer meeting pages, the audio icon does not render as large or as blurry nor would a new video icon, like in the screenshots above)
Newer mtg page w/audio icon example: https://www.fec.gov/updates/may-25-2017-open-meeting/
New icon:
play-button
Audio Icon (for reference)
speaker1

**Comment by JonellaCulmer** [comment]
Thanks @johnnyporkchops! Is that conversation about it being an arrow somewhere on github I can read? 

Would the old meeting pages be updated to reflect this new arrow? If not, I'd like it to match the old pages. And would suggest we use the existing arrow for consistency.

If we were, however, going to keep the new icon you proposed, I would only request that the arrow was filled in and not empty as it is now.

**Comment by johnnyporkchops** [comment]
Thanks @JonellaCulmer for your reply. 
For consistency, we can change the icon globally, for old and new pages.
The old video icon was not part of the new site icon-sets, it was just leftover from the old site, so it was never really legitimate.
Filling in the arrow was exactly what I thought you might suggest. I'll do that and update globally.

**Comment by johnnyporkchops** [comment]
@dorothyyeager , @JonellaCulmer What do you think about this format for showing both audio and video links for an agenda item. (inline instead of stacked)?
screen shot 2018-07-20 at 4 19 28 pm

**Pull request merged**
