### PR TITLE
5583-Feature/5544 wagtail v4.2

### LINKED ISSUE #5583: Research issues found during Wagtail 4 QA and testing
### Summary

**What we're after:**
_Wagtail 4.1.1 has so far been a successful upgrade. However, there have been a lot of changes since Wagtail v3, which we are currently using in production. We need to carefully document these changes for our content owners so that they will be informed and trained before we officially upgrade to the new version._

Content owners:
- Audit
- Press
- Public Records
- Info
- RAD

Another consideration is that [Wagtail 4.2](https://docs.wagtail.org/en/stable/releases/4.2.html) has recently been released. We may want to try it out for the upgrade.

### Related issues
- #5545 
- https://github.com/fecgov/fec-cms/pull/5576

### Completion criteria
- [ ] Create a document of changes in version 4.2 for content owners
- [ ] Attempt 4.2 upgrade
- [ ] Test 4.2 upgrade considerations

### PR DESCRIPTION
**Pull request by cnlucas**
## Summary

- Resolves #5583  and #5722 and #5580

Upgrades Wagtail to 4.2.3 
Here's[ the document ](https://docs.google.com/document/d/15QsPaXpQ21LB1MYnbOgMowgb2t4tiDQto4HmzVXOys8/edit) with my comments on 4.2 and content's comments on 4.0

### Required reviewers
2 front-end, 1 content 

## Impacted areas of the application
Wagtail

## Screenshots
Changes to Editing Toolbar (pinnable in 4.2.3)
Screen Shot 2023-05-05 at 4 54 03 PM

Screen Shot 2023-05-08 at 5 31 41 PM

## Related PRs
https://github.com/fecgov/fec-cms/pull/5576

## How to test

-  Deployed to feature currently 
-  Pick several of the items below to test (I tested document uploading on stage and it's working) 
-  re-test

NOTE-- Clicking documents/linking documents will not work on feature. The service landing page and reports landing page are both not fully editable in Wagtail. Does not work on www. See Pat's comment[ here ](https://fecgov.slack.com/archives/C3W9XBBJL/p1618348000249900?thread_ts=1618344841.249500&cid=C3W9XBBJL)

**CMS Templates**
- [x] About landing page
- [x] Alert for emergency use only
- [x] Collection page
- [x] Commissioner page
- [x] Contact page
- [X] [Custom ](https://fec-feature-cms.app.cloud.gov/help-candidates-and-committees/candidate-taking-receipts/legal-accounting-services/)page
- [x] Digest page
- [x] [ Document feed ](https://fec-feature-cms.app.cloud.gov/test_feed/)page
- [x] Document page - 
Document search sort by created is broken both in current version and 4.2
Uploading a document multiple times, didn't add extra chars for me. Double check this for someone else. 
Not sure if this is just an element of the feature space, but uploading a document and then going to [that document 404's](https://github.com/fecgov/fec-cms/issues/5545#issuecomment-1404105460). RESOLVED
- [X] Example page - This seems to be connected to the issue I'm seeing with documents not being mapped to S3 on feature--- retest on dev/stage [comment](https://github.com/fecgov/fec-cms/issues/5545#issuecomment-1404119755) RESOLVED
- [x] [Full width](https://fec-feature-cms.app.cloud.gov/help-candidates-and-committees/winding-down-candidate-campaign/full-width-page-example/) page
- [x] Home page
- [x] Home page banner announcement
        Known issue with preview of banner announcements where it shows all banners 
- [x] Legal resources landing page (Titles still aren't updating https://github.com/fecgov/fec-cms/issues/5545#issuecomment-1403817838
- [X] [Meeting](https://fec-feature-cms.app.cloud.gov/updates/december-16-2009-public-hearing-on-definition-of-federal-election-activity-rulemaking-2009/) page
- [x] Oig landing page
- [x] Press landing page
- [x] Press release page
- [x] [Record](https://fec-feature-cms.app.cloud.gov/updates/test-upcoming-record-article/) page
- [x] [Reports landing page](https://fec-feature-cms.app.cloud.gov/about/reports-about-fec/)
- [x] [Resource page](https://fec-feature-cms.app.cloud.gov/test/) - I got this to work, but probably should double check due to content [comment here](https://github.com/fecgov/fec-cms/issues/5545#issuecomment-1403961585)
- [ ]  Also test audit pages to see if it works ok and the user guide may need to be updated. ---Audit pages ok, will ask where to update guide? 
- [x] Services landing page - not working, but also not working for me on www [comment](https://github.com/fecgov/fec-cms/issues/5545#issuecomment-1403943306) [RESOLVED ](https://fecgov.slack.com/archives/C3W9XBBJL/p1618348000249900?thread_ts=1618344841.249500&cid=C3W9XBBJL)
- [x] Tips for treasurers page -[comment resolved working for me](https://fec-feature-cms.app.cloud.gov/updates/test-tip-wagtail-40-now-available/)
- [x] Snippets -

### CODE REVIEW

**Review by djgarr — APPROVED** [review]
Aside from the issue noted about the document links 404ing, checking the different pages that content uses, everything seems to be working properly

**Review by kathycarothers — APPROVED** [review]
Content standpoint all is good

**Comment by cnlucas** [comment]
> Aside from the issue noted about the document links 404ing, checking the different pages that content uses, everything seems to be working properly

I tested on stage, the document uploading issue is just because of feature. Thank you for your review!

**Review by johnnyporkchops — APPROVED** [review]
Deploys to all lower envs without issue. Tested on various environments, tested new  admin features and enhancements. Great job @patphongs and @cnluca.Also good call @cnlucas on cleaning up unused content types just before merge!

**Pull request merged**
