### PR TITLE
Feature/4352 rad form error events

### LINKED ISSUE #4352: Research adding tracking/tags to the RAD analyst form (and others) to identify errors
**What we're after:** We need to explore adding trackers to the RAD form to better understand the errors that occur repeatedly in order to make future enhancements.

**Action items:**
- Decide what we are tracking

**Completion criteria:**
- [ ] Look into how the current RAD(+) forms work, what would be involved in tracking different error states (GTM may be a challenge. Can we use custom events; look into RAD validation? Do we need to adjust form validation functionality, etc.?)
- [ ] Create any follow-up do-the-work tickets to add Trackers/tags to RAD(+) form fields to identify reoccurring error states

### PR DESCRIPTION
**Pull request by rfultz**
## Summary

- Resolves #4352 

Adding error tracking to the RAD contact form

### Required reviewers

- 1 code review
- 1 functionality review

## Impacted areas of the application

The RAD contact form's validation

## Screenshots

No visual changes

## Related PRs

None

## How to test

- We may need to test on Dev or Feature because of the security & recaptcha requirements
- Need to make sure validation errors make it to Google Analytics (the FEC account)

### CODE REVIEW

**Comment by rfultz** [comment]
@bmathesonFEC, tagging you so you know this may be headed your way

**Comment by JonellaCulmer** [comment]
@rfultz Are you putting this on feature or dev? If not, I'll need a few more instructions on how to test.

**Comment by rfultz** [comment]
@JonellaCulmer it can even work on localhost (though likely 127.0.0.1)

I've just published the non-empty GTM container for localhost (dev, stage, feature are all empty (no tracking))

**Review by patphongs — APPROVED** [review]
Looks great, thanks for demoing the event error tracking @rfultz. @JonellaCulmer Do you have any questions based on what Robert demoed? I think we should at the very least know what field had an error so that we can dive deeper into what might be the problem.

**Comment by JonellaCulmer** [comment]
> Looks great, thanks for demoing the event error tracking @rfultz. @JonellaCulmer Do you have any questions based on what Robert demoed? I think we should at the very least know what field had an error so that we can dive deeper into what might be the problem.

I agree @patphongs. I have no other comments.

**Review by JonellaCulmer — APPROVED** [review]

**Comment by rfultz** [comment]
@JonellaCulmer @patphongs cool to merge this?

**Pull request merged**
