### PR TITLE
add administratively terminated committee status

### LINKED ISSUE #4465: Modify committee profile page to display active, terminated and administratively terminated
**What we are after**
We need to make a distinction between terminated and administratively terminated committees. On the committee profile page we need to be able committees: 'terminated,' 'administratively terminated' or 'active.'

**Example**
This committee was administratively terminated. We would like to make a distinction between terminated and administratively terminated committees. 
image

**Back-end work** (potentially)
https://github.com/fecgov/openFEC/issues/4800

**Pairing**
David G. is interested in paring on this work.

**Tech steps**
- [x] Check whether `is_active == False && filing_frequency == 'A' ? Administratively terminated : Terminated` solves the need
- [x] Verify that the typeahead icons in global search and data landing page's candidate/committee search are unaffected (green only for Active) (and make sure the search for Calendar and Legal are using the same code/functionality)

**Completion criteria**
- [x] Ask Content and/or RAD if we should use `Administrative termination` or `Administratively terminated` or something else. 
- [x] Display agreed upon `Administratively terminated`, `Terminated`, or `Active` as appropriate
- [x] "Administratively terminated" will use the grey icon

### PR DESCRIPTION
**Pull request by patphongs**
## Summary

- Resolves #4465 

Adds administratively terminated to the committee profile page if they were administratively terminated.

### Required reviewers

One designer and one developer

## Impacted areas of the application

General components of the application that this PR will affect:

- Committee profile pages

### Active
Screen Shot 2021-03-31 at 5 37 22 PM

### Administratively terminated
Screen Shot 2021-03-31 at 5 36 50 PM

### Terminated
Screen Shot 2021-03-31 at 5 36 38 PM

## Related PRs

Related PRs against other branches:

branch | PR
------ | ------
feature/add_active_cmte_indicator | [link](https://github.com/fecgov/fec-cms/pull/3781)

## How to test

- Go to any committee that is active and make sure that the committee status in the header reads "Active". Ex: [http://localhost:8000/data/committee/C00409011/?cycle=2006](http://localhost:8000/data/committee/C00409011/?cycle=2006) 
- Go to any committee that is terminated and make sure that the committee status in the header reads "Terminated". Ex: [http://localhost:8000/data/committee/C00431445/?cycle=2018](http://localhost:8000/data/committee/C00431445/?cycle=2018)
- Go to any committee that is administratively terminated and make sure that the committee status in the header reads "Administratively terminated". Ex: [http://localhost:8000/data/committee/C00409011/?cycle=2018](http://localhost:8000/data/committee/C00409011/?cycle=2018). You can also see this [spreadsheet](https://docs.google.com/spreadsheets/d/1d4z-Feq_cdHNl1QCge_BsFnhCvAUfq9b/edit#gid=1769749457) 🔒 for additional examples of administratively terminated committees.

### CODE REVIEW

**Comment by JonellaCulmer** [comment]
@patphongs C00101592 still shows as Active but is listed in the spreadsheet with committees that were administratively terminated. I know there are a handful of committees that are showing up incorrectly, which adds a layer of difficulty to reviewing this PR. Wondering what your recommendations are for validating this work?

**Comment by patphongs** [comment]
> @patphongs C00101592 still shows as Active but is listed in the spreadsheet with committees that were administratively terminated. I know there are a handful of committees that are showing up incorrectly, which adds a layer of difficulty to reviewing this PR. Wondering what your recommendations are for validating this work?

This appears to be a data issue. See the [API call](https://api.open.fec.gov/v1/committee/C00101592/history/1998?per_page=1&api_key=DEMO_KEY) for that particular committee and you'll notice that the `filing_frequency` is still set to Q, which would mean that `is_active` is still `True` based on the API logic. 

We update the `filing_frequency` field manually and because of that, there are some instances where the filing frequency was not updated to `A` after the committee was sent the MS-F letter. @PaulClark2 helped to do the additional research in this [ticket](https://github.com/fecgov/openFEC/issues/4811#issuecomment-808283787) for those instances and he found "4,106 committees with single administrative termination dates that have received an MS-F but do not have a filing frequency of "A.""

@PaulClark2 suggested that we handle these data issues as they come up on an [adhoc basis](https://github.com/fecgov/openFEC/issues/4811#issuecomment-808294866). My guess is it's too much to fix all at once correct @PaulClark2?

**Review by fec-jli — APPROVED** [review]
work as expected. Great. Thanks

**Review by JonellaCulmer — APPROVED** [review]
Seems to be working as expected with the exception of the bad data. 
Thanks, @patphongs

**Pull request merged**
