### PR TITLE
5780 - Add 2012, 2008 to the presidential finance map

### LINKED ISSUE #5780: Add historic presidential election years to Presidential map
### Summary

Blocking this work is DBA Team work link TBA

**What we're after:**
_Include the historic presidential election years  2008 and 2012 to the Presidential map election years dropdown menu ._

### Completion criteria

Presidential map is live on the website, showing 2008 and 2012 Presidential summary data.

### PR DESCRIPTION
**Pull request by rfultz**
## Summary

- Resolves #5780 

Adding 2008 and 2012 to the presidential finance map

### Required reviewers

- UX?
- SMEs

## Impacted areas of the application

Only the map (after back-end/db confirm performance is acceptable)

## Screenshots

image

## Related PRs

None

## How to test
- pull the branch
- `npm run build`
- `./manage.py runserver`
- visit the [presidential finance map](http://127.0.0.1:8000/data/candidates/president/presidential-map/)
- confirm that 2012 and 2008 are options and that their data is correct

### CODE REVIEW

**Review by cnlucas — APPROVED** [review]
This is working well for me. Thanks @rfultz! I did not test exports as I could only test locally. We should probably test it on dev or stage when one is freed up.

**Comment by JonellaCulmer** [comment]
@PaulClark2 Do you mind taking a look to make sure that the exports look right? Would you like Robert to put this on feature for you to review?

**Comment by JonellaCulmer** [comment]
@rfultz Whenever you're ready, can you please put this on feature? Tricia is using dev for testing.

**Review by PaulClark2 — APPROVED** [review]
The candidate lists of 2008 and 2012 look good. The downloads work. This looks good. Thank you for all the work.

**Review by JonellaCulmer — APPROVED** [review]
Thanks for all your work on this @rfultz. I noticed that the methodology button was at the top and should be moved to the bottom, but will open a separate ticket for that. I included it in a ticket from March but it was never included in completion criteria, so it can be handled later. https://github.com/fecgov/fec-cms/issues/5641#issuecomment-1489013566

**Pull request merged**
