### PR TITLE
Update line-chart interactions

### LINKED ISSUE #2056: Line Chart interaction bug
**What we're after:** Update the raising/spending charts, currently on the CFD landing page, to that data is presented accurately and users can quickly and easily identify valuable information . 

The line chart (currently disabled) on the Campaign finance data landing page shows the totals raised and spent by entity type. Both the data (now fixed: https://github.com/fecgov/openFEC/issues/3240) and the front-end interaction need to be fixed in order to accurately provide these totals. This issue handles the front-end interaction problems. 

The line charts (one for spending, one for raising) have an issue with the mouse logic, which does not "point" to the intended target. (Ex. Hovering over May 2018, looks like June 2018). Additionally, the dashed-line marker appears as though it's on June instead of May. That is because the last day of the month is used (ex. 07/31/2018) and so the marker (dashed line) looks as though it's on the following month (08/01/2018), but it's actually very very very close to the next month. Still, that's not how it appears to onlookers, it appears as the thought the chart is inaccurate. See number 2 below.

image

The line charts can be found on feature, while they are disabled on production: https://fec-feature-cms.app.cloud.gov/data/

**Completion criteria:**
- [ ] Improve mouse logic (movecursor function in js file)
- [ ] Aggregate data by month/year, instead of month/day/year
- [ ] If unable to correct, propose alternative fix.
- Possible solutions: 
   - Replacing chart with one that can be more readily manipulated than one that is outside the current team skillset
   - Remove movecursor interaction (has usability implications) and leave only click-through

Great background information at https://github.com/fecgov/fec-cms/issues/1983

### PR DESCRIPTION
**Pull request by apburnes**
## Summary (required)

- Resolves #2056 
Fixes interaction and scale placement of line chart.

## Impacted areas of the application
This effects the `line-chart.js` and `/data` landing page.

chartbig

### CODE REVIEW

**Comment by JonellaCulmer** [comment]
@apburnes This is excellent! A huge improvement on what we had before. I just have a couple thoughts:
- The table does not function responsively. At different break points the information on the edges disappears, whether it's the Y axis on the left or the figure totals on the right. 
- There is nothing linked to the methodology button. And, unfortunately, I'm not sure what was linked there before.

**Comment by JonellaCulmer** [comment]
Per our discussion in design sync and a followup convo, we intend to add these line charts back onto the data landing page, as well as incorporate onto the advanced data pages. 

Before finalizing/merging this PR:
- [ ] We need to confirm the updated language for the "Raising breakdown" text (https://github.com/fecgov/fec-cms/issues/2293) prior to finalizing this ticket.

Updated mock-ups can be found here: https://github.com/fecgov/fec-cms/issues/2199

**Comment by JonellaCulmer** [comment]
@apburnes Here's the updated mock-up for the line charts on the Raising and spending pages:

`Raising breakdown` button language has changed to `More raising charts`. 
For spending page it will say `More spending charts`.

**Designs:**
screen shot 2018-08-28 at 2 15 05 pm

**Comment by patphongs** [comment]
@JonellaCulmer Do you think we should change the date format on the data landing page for the chart to be the same as on the raising and spending data pages? Right now data landing is formatted `Feb 28, 2017`, while the raising and spending pages are formatted `02/28/2018`.

**Comment by JonellaCulmer** [comment]
@patphongs Yes, I agree. Thanks for catching. Do you think we need a testing ticket to verify the figures one more time before merge?
@apburnes Can you make that last change? Then I'll approve because everything else looks great!

**Comment by patphongs** [comment]
> Do you think we need a testing ticket to verify the figures one more time before merge?

@JonellaCulmer Yes, it would be good to validate the numbers one more time just to be sure. I've made a testing ticket here and assigned it to @PaulClark2. You can go ahead and merge it if you think it is good to go. 

https://github.com/fecgov/fec-cms/issues/2334

**Comment by johnnyporkchops** [comment]
Does this need to be merged to dev for @PaulClark2 to test or should it remain un-merged until after testing?
https://github.com/fecgov/fec-cms/issues/2334

**Pull request merged**
