### PR TITLE
PAC & party datatable filter panel updates

### LINKED ISSUE #4687: PAC and party datatable: Display and filter option work (filter panel)
### Summary

**What we're after:**
In the PAC and party datatable, we need to remove the authorized committee filter from the datatable filter display and add missing filters. We also need to put filters within accordions per the [comp attached to the epic](https://github.com/fecgov/fec-epics/issues/204)

### Related issues

- #4651 

### Completion criteria

- [ ] PAC and party datatable reflects what is in the comp referenced above

### PR DESCRIPTION
**Pull request by patphongs**
## Summary (required)

- Resolves #4687 

Rearrange filters into accordions, removed authorized committee filters from panel

### Required reviewers

1 front end & 1 UX

## Impacted areas of the application

General components of the application that this PR will affect:

-  PAC and party datatable

## Screenshots

**Mockup**
mockup
**Actual**
Screen Shot 2021-06-30 at 2 56 51 PM

## Related PRs

Related PRs against other branches:

branch | PR
------ | ------
feature/4651-minimal-pac-party-datatable | [link](https://github.com/fecgov/fec-cms/pull/4653)
feature/4686-single-select-time-period | [link](https://github.com/fecgov/fec-cms/pull/4692)
feature/4688-pac-party-details-panel | [link](https://github.com/fecgov/fec-cms/pull/4709)

## How to test

(Include any information that may be helpful to the reviewer(s). This might include links to sample pages to test or any local environmental setup that is unusual such as environment variable (never credentials), API version to point to, etc)

- Check out this branch
- Wait for https://github.com/fecgov/openFEC/pull/4900 to be merged or check out openFEC branch `feature/4878-add-filters` and connect to the `dev` database. Follow "Steps to test" in that PR to run locally.
- Go to http://localhost:8000/data/committees/pac-party/
- Test the filters (except leadership PAC sponsor and SSFs - API needs org type added (see https://github.com/fecgov/openFEC/issues/4879)

### Future work
https://github.com/fecgov/fec-cms/issues/4690 
https://github.com/fecgov/fec-cms/issues/4737

### CODE REVIEW

**Review by johnnyporkchops — APPROVED** [review]
Filters work as expected. I found no issues.

**Comment by rfultz** [comment]
Are "Communication cost" and "Electioneering communication" committee types?

image

**Comment by JonellaCulmer** [comment]
@patphongs I'd like for Party committees to be listed separately from the "Other committees" section. We're calling it a PAC and party datatable, so I'd rather not hide them. If we find that this is confusing from usability testing, we can re-evaluate but to start I'd like them to have their own section.

**Comment by PaulClark2** [comment]
@rfultz technically "Communication cost" and "Electioneering communication" are filer types not committee types. They are not political committees, and they do not file Statements of Organization (Form 1).

**Comment by JonellaCulmer** [comment]
@PaulClark2  Should we change the filter label to say "Other committees and filers"?

**Comment by PaulClark2** [comment]
@JonellaCulmer that's a good idea. It's more accurate.

**Comment by PaulClark2** [comment]
Committee type code	|	Committee type description	|	Primary financial form
----	|	----	|	----
H	|	House	|	F3
S	|	Senate	|	F3
P	|	Presidential	|	F3P
D	|	Delegate	|	F3X
N	|	PAC - nonqualified 	|	F3X
Q	|	PAC - qualified	|	F3X
O	|	Super PAC	|	F3X
U	|	Single candidate independent expenditure	|	F3X
V	|	Hybrid PAC - nonqualified	|	F3X
W	|	Hybrid PAC -qualified 	|	F3X
X	|	Party - nonqualified	|	F3X
Y	|	Party - qualified 	|	F3X
Z	|	National party nonfederal accounts (pre-BCRA soft-money accounts)	|	SI (F3X)
I	|	Independent expenditure - person or group	|	F5
C	|	Communication cost	|	F7
E	|	Electioneering communication	|	F9

**Comment by patphongs** [comment]
After discussing with @PaulClark2 and @JonellaCulmer, we've decided to remove `Electioneering communications` and `Communication costs` from the committee types dropdown as we on are only providing Form 3X data for this datatable at this time.

**Comment by patphongs** [comment]
> @patphongs I'd like for Party committees to be listed separately from the "Other committees" section. We're calling it a PAC and party datatable, so I'd rather not hide them. If we find that this is confusing from usability testing, we can re-evaluate but to start I'd like them to have their own section.

@JonellaCulmer Is this something we are only doing in the PAC & party datatable? Should this also be implemented in the other datatables? How should those new dropdowns be labeled if we do split them out?

**Comment by patphongs** [comment]
@JonellaCulmer I have made a few changes as discussed:

1. Removed EC and CC options entirely from dropdowns
2. Split PAC and Party filters into their separate dropdowns
3. Added more tooltips per the comp

The changes I made should only pertain to this datatable. But just in case, can you double check that the Committees datatable (http://localhost:8000/data/committees/) filters have not been altered or effected? Here's the PAC and party datatable link for QA: http://localhost:8000/data/committees/pac-party/

**Comment by JonellaCulmer** [comment]
@patphongs Were we supposed to remove "independent expenditure (person or group)" as well, based on @PaulClark2's [table](https://github.com/fecgov/fec-cms/issues/4713#issuecomment-874919442) above?

**Comment by JonellaCulmer** [comment]
@patphongs Everything looks really great. One comment on the datatable breakpoint where we move the Export button to the next line. Anyway we can adjust it so that it "wraps" when it's closer to bumping up against the title?
Screen Shot 2021-07-14 at 9 39 07 AM

**Comment by patphongs** [comment]
@JonellaCulmer I've tightened up the breakpoint for the export button layout with the title. Also made the tooltip inline update for the independent expenditure committees label.

Screen Shot 2021-07-14 at 2 15 30 PM

Screen Shot 2021-07-14 at 2 15 41 PM

**Review by JonellaCulmer — APPROVED** [review]
Everything looks good to me. Tested most if not all of the filters too and everything is in good shape. The only obvious things I notice are the missing tooltips but we have a ticket in next sprint to draft those, I believe.

**Pull request merged**
