### PR TITLE
Update DEFAULT_TIME_PERIOD to be 2020

### LINKED ISSUE #2640: Update DEFAULT_TIME_PERIOD to 2020
In order for data to  reflect current time period, we need to update this hardcoded constant.
https://github.com/fecgov/fec-cms/blob/125e190f3485427190a13f48dbf7429afc3c10fd/fec/data/constants.py#L8

Double check that the line charts are also updated with this change:  #2632, https://github.com/fecgov/fec-cms/issues/2838

### PR DESCRIPTION
**Pull request by patphongs**
## Summary (required)

- Resolves #2640 
_Updating all instances of `DEFAULT_TIME_PERIOD` to be 2020 to show most up to date cycle information._

We have `DEFAULT_TIME_PERIOD` global variable referenced in both the main.jinja as a JS global var and one inside of constants.py as a python global var. Below I referenced which variable is being used on which impacted area of the application. All should now be defaulting to 2020.

In addition, I took the opportunity to do some clean up with macros and filters that were no longer being used and utilizing the global DEFAULT_TIME_PERIOD var for python files.

## Impacted areas of the application

Item | Link | Var reference
------ | ------ | ------
Raising line chart time period | http://localhost:8000/data/browse-data/?tab=raising | main.jinja
Spending line chart time period | http://localhost:8000/data/browse-data/?tab=spending | main.jinja
Transaction time period filter using partition_field macro | http://localhost:8000/data/disbursements/, http://localhost:8000/data/receipts/, http://localhost:8000/data/receipts/individual-contributions  | constants.py

### Raising line chart
Screen Shot 2019-05-24 at 11 59 57 AM

### Spending line chart
Screen Shot 2019-05-24 at 12 00 11 PM

### Transaction time period filter
Screen Shot 2019-05-24 at 12 01 49 PM

## How to test
- Go to the pages that are referenced in the "Impacted areas of the application" section above in this PR.
- Verify that defaults are now going to 2020

### CODE REVIEW

**Comment by lbeaufort** [comment]
Per our discussion, if we break these three datatables and the tests pass, we have a major gap in test coverage. I'll put in a PR to add tests for these datatables.

**Comment by patphongs** [comment]
> I think house/senate/presidential datatables aren't working with this change.
> 
> http://localhost:8000/data/browse-data/?tab=candidates

@lbeaufort Thanks for flagging the error for the candidate datatable pages. I put in a commit to restore the single_cycle macro and corresponding candidates-office-filter.jinja template.

**Comment by jason-upchurch** [comment]
> http://localhost:8000/data/candidates/house/

I get `TemplateNotFound at /data/candidates/house/`--feel free to let me know if this is on my end. I'm new to testing out cms.

**Comment by lbeaufort** [comment]
@jason-upchurch thanks for taking a look! That's the error I got too - if you pull down the latest changes, the error should go away.

**Pull request merged**
