### PR TITLE
Update .gov banner with revised text

### LINKED ISSUE #3940: Update government website banner
**What we're after:** The USWDS has updated their banner component and we should update it on our site as well. It includes new language and an icon to support websites where there's an observable lock which suggests the site is a secure one. 

https://designsystem.digital.gov/components/banner/

**Completion criteria:**
- [ ] FEC banner matches updated USWDS banner. Use "after" image as a reference

### PR DESCRIPTION
**Pull request by patphongs**
## Summary

- Resolves #3940 
_Updated language for .gov banner on our website._

## Impacted areas of the application

List general components of the application that this PR will affect:

-  .gov banner at the top of all pages

## Screenshots

Screen Shot 2020-09-17 at 10 39 46 AM

## How to test

- checkout this branch
- `npm run build` just in case for styles
- `./manage.py runserver`
- Click on the "Here's how you know ^" banner up at the top to expand it. The language should be updated as specified in the ticket.

____

### CODE REVIEW

**Review by JonellaCulmer — CHANGES_REQUESTED** [review]
Looks really great. Can we bold the word "lock"?

**Comment by patphongs** [comment]
> Looks really great. Can we bold the word "lock"?

Thanks, it's been bolded

**Review by johnnyporkchops — APPROVED** [review]
looks good

**Review by JonellaCulmer — APPROVED** [review]
Thanks, @patphongs. Looks good!

**Pull request merged**
