### PR TITLE
update language

### LINKED ISSUE #3567: Add update language above presidential accordions
### Summary
Users need to know and understand what financial data is included in the presidential map download files. 

**What we're after:**
Add language above the accordions

"The 2020 files below contain financial activity through January 31, 2020 for presidential monthly filers and through December 31, 2019 for presidential quarterly filers."

 link
image

### Completion criteria
- [ ] add update language 
- [ ] deploy hotfix

### PR DESCRIPTION
**Pull request by jason-upchurch**
## Summary (required)

- Resolves #3567

## Impacted areas of the application
List general components of the application that this PR will affect:

-  `candidates.jinja`

## How to test
- checkout branch
- http://localhost:8000/data/browse-data/?tab=candidates
Screen Shot 2020-02-21 at 10 59 32 AM

### CODE REVIEW

**Comment by dorothyyeager** [comment]
@jason-upchurch Looks good from content team perspective. You might have an extra space between the period and the < /p> in the sentence right above the new one.

**Comment by PaulClark2** [comment]
@dorothyyeager @jason-upchurch it looks like the extra space is around the `>>` I think that's probably ok. 

image

**Comment by jason-upchurch** [comment]
Screen Shot 2020-02-21 at 11 23 54 AM
@dorothyyeager this is the output now. I played around with removing a space that was previously existing in the code, but I don't see anything different. If the output doesn't look right let me know.

**Comment by jason-upchurch** [comment]
> @dorothyyeager @jason-upchurch it looks like the extra space is around the `>>` It's this bit of code, `</a> &#187; </p>`, right? ~I think that's probably ok.~ It probably doesn't hurt to remove the trailing space.
> 
> image
> @PaulClark2 that was there before, but I removed it with no effect on the output. (it's white space between the tags)

@PaulClark2 @dorothyyeager another way to look at it is: we also have the "space" before the &#187; but there is not an extra space between the last letter of the sentence and the period.

**Comment by jason-upchurch** [comment]
> Thanks for removing the trailing space. This looks good to me.

No problem at @PaulClark2 and for posterity for anyone reading this in the future, I mistook the discussion to involve a "." but as you and @dorothyyeager already know, it was the ">>" so my whole discussion above doesn't really apply! Thanks for your review and for helping me see what you both were talking about.

**Pull request merged**
