### PR TITLE
Election profile page design

### PR DESCRIPTION
**Pull request by patphongs**
## Summary

- Addresses #1970 
_Includes design improvements to the election profile pages._

## Impacted areas of the application
List general components of the application that this PR will affect:

-  Individual election profile pages. Example: [Arizona - 01](https://www.fec.gov/data/elections/house/AZ/01/2018/)

### CODE REVIEW

**Comment by patphongs** [comment]
@apburnes I've added the list of things that should be fixed before go live here:

- [ ] Disable exports for individual contributors and candidate financials datatables. Add disabled export button with "coming soon" message
- [ ] `candidate_pcc_name` has been added to the /elections endpoint. Add this to the datatable on About tab
- [ ] Reorder candidate listing on about page to sort by hidden total receipts column
- [ ] Fix right main__content--right-full so that it hugs the left nav
- [ ] Take a look at spacing for general elections use entity__figure styling from About this candidate on candidate profile page
- [ ] Fix pagination, it is not returning additional results when changing results per page set

**Comment by JonellaCulmer** [comment]
Per our discussion, @apburnes, here are some design tweaks for the election profile pages: 

On election data page:
1. Make table width consistent with existing election profile pages. The smaller tables don't fit the data very well. This would resolve two issues: candidate names cutoff for incumbents, source report column looks squished.
2. Change "Comming Soon" message for unavailable exports to "Exports coming soon."
3. Change bottom margin to 1rem below table explanatory text
screen shot 2018-06-04 at 10 28 57 am
4. Change bottom margin to 1rem on table messages that says "No data"

On about election page:
1. Add 1rem margin or padding above "state election office" body copy. 
2. Correct spelling in PCC table. "Principal" in third column is spelled incorrectly. 

TBD: Waiting on text for null state in PCC table, and any other possible changes from front-facing offices as part of their review.

**Comment by apburnes** [comment]
@JonellaCulmer wasn't sure about the "No Data" padding issue so we can go over it and the rest of the adjustments.

**Comment by JonellaCulmer** [comment]
@apburnes I missed one another thing. The section titles in the State election office section should be sentence case, not all caps. 

**Before:**
screen shot 2018-06-06 at 10 18 03 am

**After:** 
screen shot 2018-06-06 at 10 18 17 am

**Comment by JonellaCulmer** [comment]
@apburnes Here's the null state language for candidate's missing a principal campaign committee:
"No principal campaign committee identified"

cc: @AmyKort

**Comment by JonellaCulmer** [comment]
@patphongs Based on feedback received from stakeholders, we need to make the following change to the individual contributions table. 
 - [ ] Change the title of the table to "Individual contributions to candidates”

**Comment by JonellaCulmer** [comment]
@apburnes As discussed in design sync, we need to fix the IE table fix that currently directs users to the `24- and 48-Hour reports` table view and instead take users to the `Regularly scheduled reports` view.

**Comment by JonellaCulmer** [comment]
## ^^^^ Also, related to above change request ^^^^
Just a reminder that we need to go back and double check other places with Presidential stuff, such as: /election-profile-cards.jinja to make sure everything functioning as it should. 

cc: @patphongs @apburnes

**Comment by apburnes** [comment]
@JonellaCulmer try again

**Pull request merged**
