### PR TITLE
Info or alert banner above intro on ResourcePage

### LINKED ISSUE #6176: Add "Alert/informational" panel to the Resource template in Wagtail (to the top part)
### Summary

**What we're after:**
In preparation for changes to the page on Requests for Legal Consideration, we need the ability to have an "alert/informational" panel in the heading on the resource page template.

### Related issues

_List any relevant related issue(s)_

- #6163 

### Completion criteria

- [ ] Resource page template modified to add "alert/informational message panel" (screenshot under Tech steps)

### Tech steps or considerations (optional)

Screenshot of the kind of panel we want
Screenshot 2024-04-02 at 3 29 45 PM

### PR DESCRIPTION
**Pull request by johnnyporkchops**
## Summary (required)

- Resolves #6176

- Use existing `informational_message` snippet pattern  to allow an info/alert banner above intro on resource page
- Non-required field added to create/edit template for `embed_snippet`  for choosing an `info(i)` or `alert(!)` icon for the banner..Defaults to 'info' 

### Possible future work:
 Register a new snippet model for `info/alert` banner and one for a  more `generic snippet`  that could be used for the `Cont limits footnotes`, for example. Currently content team is storing the html for Cont limits footnotes in snippets and pasting it into html blocks on pages instead of using a snippet chooser because of the default styling of the embed snippet template. New snippet patterns would also make the snippets listed separately in the admin, which content team has complained is currently hard to browse and find what your looking for..

### Required reviewers

One Content
Optional: One Dev or UX

## Impacted areas of the application

General components of the application that this PR will affect:

- Resource pages intro section
- Emded_snippet editing interface

### Info:

Screenshot 2024-04-25 at 1 21 59 AM

### Alert:

Screenshot 2024-04-25 at 1 21 21 AM

## How to test
-[ ] **Remove stage deploy task before merge**

**Content/UX tem:**
This is on stage  for testing

**Developers/UX team:**
- Checkout and run `manage.py migrate`
- Create or edit existing ResourcePage and add a new or existing informational banner above the intro using the intro streamfield
- Test changing the banner_icon from the default of 'info' to 'alert'
- This should not effect any existing ages that use `embed snippet` for Contribution limits tables/footnotes/info messages, but you can spot check them to be sure.

### CODE REVIEW

**Comment by dorothyyeager** [comment]
@johnnyporkchops Whenever you're ready to push into a testing space, happy to look at it!

**Comment by johnnyporkchops** [comment]
@

> @johnnyporkchops Whenever you're ready to push into a testing space, happy to look at it!

@dorothyyeager , this is on `https://stage.fec.gov` for testing

**Review by dorothyyeager — CHANGES_REQUESTED** [review]
@johnnyporkchops - All looks good and I created the snippet we'll need and inserted it on the page it's going on. The one thing is that we wanted to link a Record article, but I don't see a way to insert a link into the text. Is there a way to do that?

image

p.s. That is not the final text of the snippet, need to edit that. But main thing to fix for the PR is ability to add a link within a snippet. Thanks!

**Comment by johnnyporkchops** [comment]
> The one thing is that we wanted to link a Record article, but I don't see a way to insert a link into the text. Is there a way to do that?


@dorothyyeager You would add the link the same way you add it to any of the other snippets...with html

**Review by dorothyyeager — APPROVED** [review]
@johnnyporkchops showed me how html can be used within the snippet and we are good to go! Approved and will get the job done for the legal requests for consideration page. Thank you John!

**Review by patphongs — APPROVED** [review]
Looks good 👍

**Pull request merged**
