### PR TITLE
Rename ReportingExamplePage to Example Page, add features

### LINKED ISSUE #3149: Create Example Page template in Wagtail
### Summary

To assist with our upcoming work in making disclaimer examples and keep Wagtail tidy and easy for content managers, we'd like to make a new template similar to the reporting example template, but called "Example page"

### Proposed Behavior / Feature

We'd like the template to work like this one (https://fec-prod-proxy.app.cloud.gov/admin/pages/add/home/reportingexamplepage), but be called "Example page." We'd like to have a few other features added, such as embeddable video and internal/external buttons.

Here's a screenshot of the reporting example template:

image

For this template, we'd like to add the following options to what's already in the reporting example template:
- image into the body portion (similar to what's available in custom/resource page templates)
- video embed into the body portion  (similar to what's available in custom/resource page templates)
- internal button into the body portion (See #2935 for background on this button)
- external button into the body portion  (See #2935 for background on this button)
- "Example" added as an option into "pre-title" drop down

### Use Case

Users who will love the examples we are making of proper disclaimers. (Currently being drafted in #3148 )

## Completion criteria ##
- [ ] Add the requested features listed above into the requested new template (based off the reporting example template)
- [ ] Testing by content team to ensure it has what we need for the disclaimer examples in #3148

### PR DESCRIPTION
**Pull request by johnnyporkchops**
## Summary
Rename ReportingExamplePage to Example Page, add features
        - Resolves #3149

- Rename ReportingExample page to ExamplePage
- makemigrations/migrate
- Add new features to ExamplePage 
- makemigrations
- Restore local database to latest dump
- Combine the operations in the last two migrations above by manually editing the first to include operatons from the second * and then delete the second file .(rename page first, then add new features.) This way I only push one new migration file up.
- migrate again
***Note:** If I had renamed the model and added new features in the same makemigrations action, Django would have considered the ExamplePage as a whole new model and deleted the ReportingExamplePage model , making existing pages based on that would not work, as I found in testing. If the model is exactly the same but has a new name, Django asks if you intended to just rename it. Then you can add your new features to the model and migrate again without breaking pages created  under the old name.

- [ ] Followup issue: Its probably a good time to squash migrations. See https://github.com/fecgov/fec-cms/issues/3094 and [Django Docs](https://docs.djangoproject.com/en/2.2/topics/migrations/#squashing-migrations): 

## Impacted areas of the application
new file:   home/migrations/0106_auto_20191101_1759.py
modified:   home/models.py
modified:   home/templates/home/reporting_example_page.html

## How to test
**Content team:** This can be tested on feature space https://fec-feature-cms.app.cloud.gov/admin
Don't forget to test existing pages that were created originally with ReportingExampePage before it was renamed:
Go to `Add Child Page` > on the far right column of the page types listing you can click on `Pages using Example page` and spot check that these pages match what is on production

**Developers:** 
1) Checkout `feature/3149-ExamplePage-template-wagtail`
2) `./manage.py migrate`
3) Go to Wagtail admin: http://localhost:8000/admin
4) Create and preview/publish a page of type ExamplePage
5) Test the image, external-link, internal-link blocks
6) Embed a video using the Paragraph blocks RTE embed media option
7) It is also important to spot-check existing pages that were created originally with ReportingExamplePage template, before it was renamed.
Go to `Add Child Page` > on the far right column of the page types listing you can click on `Pages using Example page` and spot-check that these pages match what is on production

### CODE REVIEW

**Comment by johnnyporkchops** [comment]
@dyeager you can add vide embed code via the rich text box `paragraph` or html called `html`

**Comment by johnnyporkchops** [comment]
@dorothyyeager , With the name change, we would no longer have ReportingExamplePage, just ExampePage template ? Is that what you mean?

**Comment by johnnyporkchops** [comment]
@dorothyyeager , The page has been renamed and new features added, so I re-requested your review. This is on feature-space for testing

**Comment by dorothyyeager** [comment]
Merging since @rfultz advises this is good to go.

**Pull request merged**
