### PR TITLE
Feature/5278 election year filters for election summaries

### LINKED ISSUE #5278: All elections totals table: Change the dropdown to show by election year for Senate and House
### Summary

**What we're after:**
Change the dropdown to show by election year for House and Senate election profile pages. The data represented is data across the entire Senate and House election periods.

We currently pass election year in the API. This would be a front-end change to filter by election year instead of two-year period.

API endpoint: https://api.open.fec.gov/v1/candidates/totals/aggregates/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&sort=state&per_page=10&page=1&aggregate_by=office-state&election_year=2022&office=S&election_full=true&is_active_candidate=true 

**Page links:**
Senate: https://www.fec.gov/data/elections/senate/
House: https://www.fec.gov/data/elections/house/

### Completion criteria

- [ ] Dropdown is updated to election year for house and senate
- [ ] Full totals are verified as accurate

### PR DESCRIPTION
**Pull request by rfultz**
## Summary

- Resolves #5278 

Changing the election totals filters from `min_election_cycle` and `max_election_cycle` to `election_year` values

### Required reviewers
(Feel free to remove yourself)
- front-end for code/approach
- back-end for data?
- SME for accuracy

## Impacted areas of the application

Only the 'contributions over time' section for the [House](http://127.0.0.1:8000/data/elections/house/) and [Senate](http://127.0.0.1:8000/data/elections/senate/) elections pages

## Screenshots

No visible changes

## Related PRs

None

## How to test

- pull the branch
- `npm run build`
- `./manage.py runserver`
- Check the date range pulldowns in the 'contributions over time' section of the [House elections page](http://127.0.0.1:8000/data/elections/house/)
- Check the date range pulldowns in the 'contributions over time' section of the [Senate elections page](http://127.0.0.1:8000/data/elections/senate/)

### CODE REVIEW

**Review by cnlucas — APPROVED** [review]
Working well for me, thanks @rfultz. Just for my own clarification, why did this change need to happen? I couldn't figure it out from the ticket.

**Review by johnnyporkchops — APPROVED** [review]
Works as expected,  nice job refining the logic as well.

**Comment by JonellaCulmer** [comment]
@rfultz Do you mind posting a screenshot of the update dropdowns? I can't run locally.

**Comment by rfultz** [comment]
@JonellaCulmer @PaulClark2 this is on Feature now

**Pull request merged**
