### PR TITLE
Fix H/S/P candidate datatable breadcrumb capitalization

### LINKED ISSUE #2932: H/S/P Candidate datatable breadcrumbs need to be capitalized properly
H/S/P Candidate datatable breadcrumbs need to be capitalized properly.

https://www.fec.gov/data/candidates/house/
https://www.fec.gov/data/candidates/senate/?election_year=2020&cycle=2020&election_full=true
https://www.fec.gov/data/candidates/president/?election_year=2020&cycle=2020&election_full=true

image

Should say: `Candidates for House`, `Candidates for Senate`, `Candidates for president` per @JonellaCulmer

### PR DESCRIPTION
**Pull request by lbeaufort**
## Summary (required)

- Resolves #2932 

## Impacted areas of the application
List general components of the application that this PR will affect:

-  House/Senate/Presidential candidate datatables

### Before
Screen Shot 2019-05-31 at 12 03 12 PM
Screen Shot 2019-05-31 at 4 36 03 PM
Screen Shot 2019-06-03 at 12 18 23 PM

### After
Screen Shot 2019-05-31 at 4 37 02 PM
Screen Shot 2019-05-31 at 4 37 08 PM
Screen Shot 2019-06-03 at 12 18 06 PM

## How to test
http://localhost:8000/data/candidates/house/
http://localhost:8000/data/candidates/senate/?election_year=2020&cycle=2020&election_full=true
http://localhost:8000/data/candidates/president/?election_year=2020&cycle=2020&election_full=true

### CODE REVIEW

**Comment by JonellaCulmer** [comment]
Should we also change the header on the Candidates for President datatable to include a lowercase p? 
cc: @AmyKort

**Comment by AmyKort** [comment]
Yes, it should be "Candidates for president." Thanks for catching that, @JonellaCulmer .

**Comment by JonellaCulmer** [comment]
@lbeaufort Think you can incorporate the header fix into this PR, or would you prefer we opened a separate ticket?

**Comment by lbeaufort** [comment]
@JonellaCulmer I incorporated the changes into this ticket, and discovered that the datatable loading issue was actually a bug, thanks for catching it! Can you re-test please?

**Pull request merged**
