### PR TITLE
[DON'T MERGE] 5641 - 2024 presidential map

### LINKED ISSUE #5641: Presidential Map 2024
**What are we after:**
We're going to continue to add presidential election cycles to the presidential map. In anticipation of that work, we need to modify the toggle year selector to a dropdown select. 

**Related work:**
Previous epic work: https://github.com/fecgov/fec-epics/issues/174

**Action items:**
- [x] Bubbles are removed 
- [x] "Candidates running in" filter is now a dropdown selector
- [x] 2024 is added

**Completion criteria:**
- [x] Presidential map is updated for 2024 election

### PR DESCRIPTION
**Pull request by rfultz**
## Summary

- Resolves #5641 

Updated the presidential finance map to get ready for 2024 and include previous years (if API will support it)

### Required reviewers

- 1 front-end
- 1 UX
- 1 back-end/db?
- 1 product owner?

## Impacted areas of the application

Only the presidential map is affected

## Screenshots

image

image

## Related PRs

None

## How to test

- Pull the branch
- npm i
- npm run build
- Check the [presidential map](http://127.0.0.1:8000/data/candidates/president/presidential-map/)
- **Known issues**
   - At this point, 2024 data doesn't exist so
   - the map default to 2020.
   - At this point, data before 2016 doesn't exist (not sure whether it will)

### CODE REVIEW

**Comment by JonellaCulmer** [comment]
@PaulClark2 @patphongs @AmyKort Do we plan to keep data going back to 2008 forever or indefinitely?

**Comment by patphongs** [comment]
> Do we plan to keep data going back to 2008 forever or indefinitely?

@JonellaCulmer @rfultz I believe our [first iteration](https://github.com/fecgov/openFEC/issues/5363) will be just with 2024, 2020, and 2016 data for now. The [2012 and 2008](https://github.com/fecgov/openFEC/issues/5363) data still requires more back end work to include it and can be done in the future. But prior to including, results of the load testing of the presidential map API endpoints will help @AmyKort @PaulClark2 and I decide if we will be able to handle the additional presidential election years prior to 2016.

**Comment by PaulClark2** [comment]
Yes, that's what we discussed. I think the DB folks had some concerns about performance if we included 2008 and 2012 right now. I would like to eventually include that data, but for our initial 2024 release 2024, 2020 and 2016 presidential data is good.

**Comment by JonellaCulmer** [comment]
@rfultz Do you mind changing the toggle to a dropdown for the "candidates running in" years filter?

**Comment by rfultz** [comment]
> @rfultz Do you mind changing the toggle to a dropdown for the "candidates running in" years filter?

A real <select> element or <div>s that look like a pretty pull-down? Either would be new functionality for this widget.

Is it less of a concern if there will only be the three election year options instead of the five in this what-if demo?

**Pull request closed without merging**
